sqlc-dev/sqlc

internal/catalog/build.go, internal/catalog/build_test.go, internal/pg/catalog.go, internal/pg/errors.go
The main goal of the new catalog package is to contain less information. The current `postgres` package has too much information about things, such as `GoName` and `GoType`. 
Long term, I'd like to be able to build out `pg.Catalog` both from SQL and a live database.
=> Add the second generation system catalog

internal/dinosql/parser.go
Tests would fail randomly when tables would be in different order
=> Sort tables and enums in schema

internal/catalog/build.go, internal/catalog/build_test.go
Before, this would result in
column "venues_id_pkey" of relation "venues" does not exist
=> catalog: support "ALTER TABLE ... DROP CONSTRAINT ..."

internal/catalog/build.go, internal/cmd/cmd.go, internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/query_test.go
This change gets us closer to generating the ideal code for the query @srenatus posted in #7. Currently, the output looks like:
```go
const deleteToken = `-- name: DeleteToken :exec
DELETE FROM chef_authn_tokens cat
WHERE cat.id=$1
AND projects_match(cat.project_ids, $2::TEXT[])
`
type DeleteTokenParams struct {
ID      string
Dollar2 []string
}
func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
_, err := q.db.ExecContext(ctx, deleteToken, arg.ID, pq.Array(arg.Dollar2))
return err
}
```
=> Add support for cast operations

internal/catalog/build_test.go, internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/dinosql/soup.go, internal/pg/catalog.go
- Add initial support for JOIN queries. Fixes #27
- Use `sql.NullInt64` for null bigint columns
- Correctly expand `table.*` column names in queries
- Support multi-assignement UPDATE statements
=> A smorgasbord of fixes

README.md, internal/cmd/cmd.go, internal/dinosql/checks_test.go, internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/dinosql/testdata/ondeck/sqlc.json
- `name` in the package config is now optional
- return an error if package path is empty
- `schema` and `queries` can point to individual files
- the package path is automatically created if it does not exist
Fixes #67
=> A few quality of life improvements

internal/cmd/cmd.go
Before this change, sqlc would write files as soon as code was
generated. Now, only output code if the entire parsing and generation
passes are clean, for all packages.
=> cmd: Do not output any changes on error

internal/catalog/build.go, internal/dinosql/checks.go, internal/dinosql/checks_test.go, internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/pg/errors.go
Annotate error messages with node location, if available
```sql
CREATE TABLE foo (bar text);
SELECT *
FROM bar;
```
```text
queriy.sql:3:1: relation "bar" does not exist
queriy.sql:4:6: relation "bar" does not exist
```
=> pg: Add location to errors

internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/pg/catalog.go
Range values may be scoped to a specific schema. If that's the case,
make sure to search the correct schema for tables and columns.
Fixes #80
=> parser: Use schema when resolving catalog refs

internal/dinosql/gen.go
Assign the error value to _ if no queries exist, so the file still
compiles. This is an edge case so I'm not sure it's worth thinking
more about.
Fixes #94.
=> internal/dinosql: Prepare() with no GoQueries still valid

internal/dinosql/gen.go
Before adding imports for used packages, make sure that they do not
exist in the override types.
Fixes #97
=> gen: Generate single import for uuid package

README.md, examples/any.md
7 extra characters ensures that we don't accidentally fetch a bunch of
rows into memory and immediately discard them.
=> README: add LIMIT 1 to query that should return one

internal/dinosql/parser.go, internal/dinosql/query_test.go
While this is a fix for #103, it's not a long term solution. We need to be smarter about determining the type of parameters.
Fixes #103
=> parser: Support function calls in expressions

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/pg/catalog.go, internal/postgres/schema.go
When two tables have identical columns, pick the correct struct to
return.
Fixes #106
=> gen: Pick correct struct to return for queries

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/dinosql/query_test.go, internal/dinosql/testdata/ondeck/city.sql.go, internal/dinosql/testdata/ondeck/models.go, internal/dinosql/testdata/ondeck/sqlc.json, internal/dinosql/testdata/ondeck/venue.sql.go
A field's JSON tag value should be the name of the column as it appears
in the database.
Fixes #108
=> gen: Create consistent JSON tags

README.md, internal/cmd/cmd.go, internal/dinosql/config.go, internal/dinosql/config_test.go, internal/dinosql/parser.go, internal/dinosql/testdata/ondeck/sqlc.json
Configuration files must now have a version set. 
```
{
"version": "1",
"packages": [...]
}
```
Thanks to @inconshreveable for the suggestion. This will be an annoying update for the early adopters, but I think it's worth the pain for all future sqlc users.
Fixes #113
=> Add version to configuration file

internal/dinosql/parser.go, internal/dinosql/query_test.go
Before this change, invalid query comments would result in a panic. Add a first pass at validation. In the future, we'll need to switch to a true parser for these comments.
Fix #114
=> Validate metadata from comment string

internal/dinosql/gen.go
Without this, you'll get prepare errors but have no idea which query failed to prepare.
=> wrap prepare errors with query name for easier debugging

internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/prepared/db.go
When using prepared queries, generate a method to close all the prepared
queries.
Fixes #101
=> gen: Add Close method to Queries struct

README.md, internal/catalog/build.go, internal/catalog/build_test.go, internal/dinosql/config.go, internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/parser.go, internal/dinosql/query_test.go
Often a user may want to override the Go type used for model
generation and query generation, but it's not a 1-to-1 mapping
of SQL types to Go type. Instead, the override to use depends
entirely on the column of a particular table. This commit adds the
functionality to override types of generated columns in models and query
parameters by adding a new 'overrides' configuration settings object
on a per-package basis.
This required tracking down a number of places where the column's Table
FQN wasn't properly propagated through to the the model or query
parameter Column. This change necessitated updating a bunch of tests to
match.
Lastly, I've added a test to prove the functionality works (in addition
to testing it on a large code base) and added a documentation section in
the README.
=> Implement per-column type overrides.

internal/dinosql/gen.go
The previous `goInnerType` assumed that the column name and table would
be non-empty. For computed columns, this is not true. Make sure to check
if the override setting (PostgresType or Column) is non-empty before
applying an override.
I discovered this with a query that was cast a parameter to a boolean. The generated code assigned the parameter a type of `uuid.UUID`.
```sql
SELECT * from authors
WHERE $3::bool
ORDER BY id
LIMIT $2;
```
=> gen: Ignore empty override settings

internal/dinosql/parser.go, internal/dinosql/query_test.go
If a query specifies a return value (:one or :many), require that
statements have a RETURNING clause.
Fixes #121
```
$ sqlc generate
query/city.sql:26:1: query "DeleteCity" specifies parameter ":one" without containing a RETURNING clause
```
=> parser: Return error if missing RETURNING

internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/postgres/types.go
Also, don't leave out expressions we haven't added. Instead, generate a
column with an "any" type.
Fixes #122
=> parser: Add support for mathmatical operators

internal/dinosql/parser.go, internal/dinosql/query_test.go
More complex case expressions will generate columns with the `any` type.
Fixes #92
=> parser: Add support for simple case expressions

internal/dinosql/checks.go, internal/dinosql/parser.go, internal/dinosql/query_test.go
Error if the length of the target columns do not match the length of the
value expressions.
Trim space off comments before splitting. Trailing whitespace should not
causing parsing metadata to fail.
Fixes #56
=> parser: Error on mismatched INSERT input

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/testdata/ondeck/city.sql.go, internal/dinosql/testdata/ondeck/prepared/city.sql.go, internal/dinosql/testdata/ondeck/query/city.sql
Remove comments from SQL and add them as Go comments
Fixes #102
=> gen: Turn SQL comments into Go comments

README.md, examples/any.md, examples/delete.md, examples/insert.md, examples/prepared_query.md, examples/query_count.md, examples/query_one.md, examples/returning.md, examples/transactions.md, examples/update.md, internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/db.go, internal/dinosql/testdata/ondeck/prepared/db.go
This change includes several enhancements:
1. Add the `blob` type
2. Add the `inet` type and import for the `"net"` package as necessary
3. Fixes the "uses" functions so that they work with array columns
4. Export the `DBTX` interface. The unexported type didn't play well with [wire](https://github.com/google/wire) which needs concrete types which requires them to be exported. That said, since this interface is always the same, maybe there should be a type directly exported by sqlc, e.g. `"github.com/kyleconroy/sqlc.DBTX"` instead.
5. Fixes some minor lint issues
=> Add a few types, export DBTX

internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/city.sql.go, internal/dinosql/testdata/ondeck/prepared/city.sql.go, internal/dinosql/testdata/ondeck/query/city.sql
Previously if a SQL comment spanned multiple lines they'd all be run
together like this:
// Comment line one// Comment line two //Comment line three
Instead, print each comment line on its own Go line. Update the tests
to expose the problem and also test that it's fixed properly.
=> internal/dinosql: fix multiline comment rendering

internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/db_test.go, internal/dinosql/testdata/ondeck/models.go, internal/dinosql/testdata/ondeck/prepared/models.go, internal/dinosql/testdata/ondeck/prepared/venue.sql.go, internal/dinosql/testdata/ondeck/query/venue.sql, internal/dinosql/testdata/ondeck/schema/0002_venue.sql, internal/dinosql/testdata/ondeck/venue.sql.go
The enum issue may only be because I am using a column with an array of enums.
Also, `Scan()` can panic if it's not passed a `[]byte`. I can have it return an error instead, but that requires importing `fmt` or `errors`, wasn't sure if it was worth the trouble. Thoughts?
=> fix scanning into enums

internal/dinosql/testdata/ondeck/Makefile
This is an example of how to set up sqlc targets with Make to
automatically regenerate the files when an input changes.
=> internal/dinosql/testdata/ondeck: add Makefile

internal/dinosql/gen.go
Before this change it was possible to generate duplicate import statements.
Take this schema:
```json
{
"version": "1",
"packages": [{
"schema": "schema.sql",
"queries": "queries.sql",
"name": "queries",
"path": "."
}],
"overrides": [
{ "column": "toy.owner_id", "go_type": "database/sql.NullInt64" },
{ "column": "toy.manufacturer_id", "go_type": "database/sql.NullInt64" }
]
}
```
That would generate a `models.go` file with two imports for `database/sql`.
What the change here does is to make all imports, in the queries and the
models file, unique.
=> Avoid duplicate import statements

internal/catalog/build.go, internal/catalog/build_test.go
Arguments to SQL functions are not required to have a name.
Also add a test for `DROP FUNCTION [IF EXISTS]`
=> internal/catalog: Parse unnamed function arguments

internal/dinosql/gen.go, internal/dinosql/gen_test.go
> The SQL standard requires that writing just timestamp be equivalent to
> timestamp without time zone, and PostgreSQL honors that behavior.
> timestamptz is accepted as an abbreviation for timestamp with time zone;
> this is a PostgreSQL extension.
Fixes #168
=> internal/dinosql: Add support for timestamptz

internal/cmd/cmd.go, internal/dinosql/parser.go
This fixes https://github.com/kyleconroy/sqlc/issues/174 and https://github.com/kyleconroy/sqlc/issues/176.
`parseQuery` used to return a `nil` query and a `nil` error, however the code relies on the assumption that the query is always valid if the error is not `nil` (as explained [here](https://github.com/kyleconroy/sqlc/issues/176#issue-538122582)).
This assumption gets correct with this change. `parseQuery` returns either a query _or_ and error. There's no `return nil, nil` anymore.
=> parseQuery: Return either a query or an error

internal/dinosql/parser.go
This is an alternate fix for #176 that allows the `schema` and `queries` value for a package to be the same directory or SQL file. I'd like to support this use case for example code. It's useful to have a single SQL file with both the DDL and query statements.
If no queries can be found, sqlc will return an error message instead of panicing.
=> internal/dinosql: Error on missing queries

internal/dinosql/gen.go, internal/dinosql/gen_test.go
Use sql.NullInt32 and sql.NullTime
Fixes #76
=> internal/dinosql: Use more database/sql null types

internal/catalog/build_test.go, internal/dinosql/parser.go, internal/pg/catalog.go
The schema is removed from the catalog so that queries can not
reference it, since it will be empty in a new session.
Fixes #181
=> internal/dinosql: Support the pg_temp schema

internal/dinosql/gen.go, internal/dinosql/gen_test.go
This is a short-term fix for #172. Longer term, we're going to need to decide how to apply overrides to array types.
Fixes #172
=> internal/dinosql: Override columns with array type

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/dinosql/query_test.go
Expands `SELECT *` into the correct columns, no matter the location
Fixes #173
=> internal/dinosql: Implement robust expansion

internal/catalog/build.go, internal/catalog/build_test.go, internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/models.go, internal/dinosql/testdata/ondeck/prepared/models.go, internal/dinosql/testdata/ondeck/schema/0002_venue.sql, internal/pg/catalog.go
Comments are supported for SCHEMA, TABLE, COLUMN, and TYPE.
Fixes #187
=> internal/dinosql: Add COMMENT ON support

internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/query_test.go
Generate the correct types for `DATE`, `TIME [WITHOUT TIME ZONE]`, `TIME WITH TIME ZONE`
Fixes #195
=> internal/dinosql: Add DATE support

internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/models.go, internal/dinosql/testdata/ondeck/prepared/models.go, internal/dinosql/testdata/ondeck/schema/0002_venue.sql
Ensure that enum identifiers are valid
Fixes #197
=> internal/dinosql: Filter out invalid characters

internal/cmd/cmd.go, internal/dinosql/parser.go
I added a new check that returns an error when a package contains no queries. However, I mistakenly put this check before the check for parser errors. Moving the error below the `merr.Errs` ensures that the reported error message makes sense.
Fixes #206
=> internal/dinosql: Return parser errors first

internal/dinosql/parser.go
Fixes https://github.com/kyleconroy/sqlc/issues/201.
A query like this caused incorrect field names for `LIMIT` and `OFFSET`:
```sql
-- name: GetFoo :one
SELECT
(SELECT 1) AS baz
FROM foo
WHERE
bar = $1
LIMIT $2
OFFSET $3;
```
The generated struct used to look like this:
```go
type GetFooParams struct {
Bar   string `json:"bar"`
Bar_2 string `json:"bar_2"`
Bar_3 string `json:"bar_3"`
}
```
This happened because `LIMIT` and `OFFSET` are `nil` for the subquery but they've been assigned to the `paramSearch` though.
=> Generating correct LIMIT and OFFSET field names

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/pg/catalog.go, internal/pg/functions_admin.go, internal/pg/pg_catalog.go
=> internal/dinosql: Implement advisory locks

internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/pg/functions_string.go, internal/pg/pg_catalog.go
Fixes #214 
Adding support for advisory locks in #212 broke code generation for the queries that used functions with parameter references. This change restores some of that functionality. The only difference is the name of the field on the parameter struct.
```sql
SELECT * FROM company_users WHERE company_slug = $1 AND email = LOWER($2);
```
used to generate
```
type Params struct {
CompanySlug string
Email string
}
```
but will now generate
```
type Params struct {
CompanySlug string
Lower string
}
```
I know that's not ideal, but I thought it would be better to provide a hot fix.
=> dinosql/internal: Add lower and upper functions

internal/catalog/build.go
sqlc does not support sequence DDL currently. Ignore DDL that touches
sequences.
Fixes #217
=> dinosql/internal: Ignore alter sequence commands

internal/dinosql/parser.go
Fixes #220 
Repeating a duplicate query name will now result in the following error:
```
query.sql:1:1: duplicate query name: GetReportByID
```
=> internal/dinosql: Error on duplicate query names

internal/dinosql/gen.go, internal/dinosql/gen_test.go
Enums of type enum_type with values like foo-bar should be named
EnumTypeFooBar, but were being generated as EnumTypeFoobar.
The regex pattern I was using to remove unsupported characters was
accidentally stripping out underscores, the character used to split the
string.
Fixes #222
=> internal/dinosql: Fix incorrect enum names

internal/dinosql/gen.go, internal/dinosql/gen_test.go
Since the Go standard library does not have a decimal type, lib/pq returns decimals and numerics as strings. You'll need to use a decimal library to properly support these values.
https://github.com/lib/pq/issues/648
Fixes #227
=> internal/dinosql: Add support for numeric types

internal/cmd/cmd.go
The `cmd.Do` function takes a writer to use as standard out, but doesn't
use it. Instead, there's a duplicate call to `cobra.Command.SetErr`.
This patch replaces one of the duplicates with `SetOut`.
=> Set stdout correctly

internal/dinosql/gen.go, internal/mysql/parse.go
This corrects all the places where fmt.Errorf wasn't already using the %w
directive for wrapping errors. A small quality of life change.
Found all of these with
ag --no-heading 'fmt\.Errorf\(.*, err'  | grep -v '%w'
=> use %w for wrapping errors in fmt.Errorf

internal/cmd/cmd.go, internal/mysql/errors.go, internal/mysql/errors_test.go, internal/mysql/parse.go, internal/mysql/schema.go
Addresses  #245 
```
❯ sqlc generate
booktest/mysql/query.sql:14:7: syntax error at or near 'SELEC'
❯ sqlc generate
booktest/mysql/query.sql:13:1: column "id" not found in table "books"
```
Note that the MySQL parser does not offer the same interface as the `pg` parser for inspecting the context of syntax errors. With this restraint, this PR uses regex matches on the `error` messages to parse the information. I don't feel great about the dependence on the contents of the `sqlparser` error message but I'm not sure how else to extract the required information...
=> Improved MySQL errors

examples/booktest/mysql/query.sql.go, internal/dinosql/gen.go, internal/mysql/README.md, internal/mysql/functions.go, internal/mysql/gen.go, internal/mysql/param_test.go, internal/mysql/parse.go, internal/mysql/parse_test.go, internal/mysql/schema.go
This PR contains additional improvements to MySQL support
- now supports unqualified column expressions in the `SELECT` expression for the "left-most" table in the `FROM` expression. This is consistent with the MySQL specification.
- adds support for more MySQL datatypes and function return types
- adds logic to reuse `structs` when all fields are selected from a table
On a separate note, _please consider not squashing the commit history_. As the project grows and new collaborators seek to contribute, a rich git history along with its associated metadata is very helpful! I also personally find it incredibly useful as I navigate a project.
=> MySQL support improvements

README.md, internal/dinosql/config.go
If I try to import from a package named "go-x" or "x-go" it will
generate a syntax error. We should do the right thing and determine
what the package name is and set it to that, but in lieu of that,
a good guess for the import name is just stripping that prefix or
suffix.
Updates #261.
=> internal/dinosql: strip leading "go-" or trailing "-go" from import

README.md, internal/dinosql/config.go, internal/dinosql/config_test.go, internal/dinosql/gen.go
The `go_type` value in an override can now reference a basic type, such
as "string" or "bool".
Fixes #260
=> internal/dinosql: Overrides can now be basic types

internal/dinosql/parser.go, internal/pg/errors.go
Previously we only populated the CTE field if the outer query was
a SELECT, but there's no reason you can't use a CTE with an UPDATE.
Fixes #267.
=> internal: allow CTE to be used with UPDATE

internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/mysql/param_test.go, internal/mysql/parse.go, internal/mysql/parse_test.go, internal/mysql/test_data/queries.sql
```sql
/* naame: CreateAuthor :exec */
INSERT INTO authors (name) VALUES (?);
```
This query fails silently and does not generate a `go` query.
Given the similarity of metadata syntax between `mysql` and `pg`, it seems appropriate to consolidate the logic.
=> improves MySQL query metadata parsing

examples/booktest/mysql/query.sql, examples/booktest/mysql/query.sql.go, internal/mysql/param.go, internal/mysql/param_test.go, internal/mysql/parse.go, internal/mysql/schema.go
Adds functionality described in #71 
As is, the current implementation supports both `sqlc.arg(ParamName)` and `:ParamName`.
=> adds mysql support for custom `sqlc.arg(MyParam)` params

internal/cmd/cmd.go, internal/cmd/generate.go, internal/config/config.go, internal/config/config_test.go, internal/dinosql/gen.go, internal/dinosql/parser.go, internal/mysql/errors_test.go, internal/mysql/gen.go, internal/mysql/gen_test.go, internal/mysql/param_test.go, internal/mysql/parse.go, internal/mysql/parse_test.go
In preparation for #302, I'm moving all configuration types and logic to a separate package.
=> internal/config: Create new config package

examples/authors/db_test.go
The tests in the examples directory should only run if the `examples` build tag is included:
```
go test -tags examples ./...
```
=> examples: Add build tag to authors tests

docs/migrations.md, internal/dinosql/migrations_test.go, internal/dinosql/parser.go
We use [golang-migrate](https://github.com/golang-migrate/migrate) for migration management, and would like to be able to use it with sqlc. The obstacle here is that it doesn't indicate up/down migrations through special comments, but by naming the SQL files things like 
```
1481574547_create_users_table.up.sql
1481574547_create_users_table.down.sql
```
so I've had to put the check in `ReadSQLFiles` and test the functionality differently.
Let me know if you'd like any of this done differently, I'm happy to keep tweaking it.
=> internal/dinosql: ignore golang-migrate rollbacks

internal/cmd/cmd.go
The parse command no longer makes sense in the multi-engine. I may bring back a similar command.
Fixes #278
=> cmd: Remove parse subcommand

internal/dinosql/parser.go, internal/endtoend/testdata/star_expansion_cte/go/query.sql.go, internal/endtoend/testdata/star_expansion_cte/query.sql
Before this change, queries with multiple CTEs referring to previous CTEs would fail. The query catalog is now passed around correctly.
Fixes #269
=> internal/parser: Resolve nested CTEs

internal/dinosql/parser.go, internal/endtoend/testdata/missing_semicolon/query.sql, internal/endtoend/testdata/missing_semicolon/sqlc.json
If the last query in the file does not have a semicolon, return an error
Fixes #265
=> internal/parser: Error if last query is missing

internal/dinosql/gen.go, internal/dinosql/kotlin/gen.go
Multi-line SQL comments broke the code generator. This PR fixes the issue.
**The case:** Consider this SQL schema:
```sql
CREATE TABLE authors (
id   bigserial PRIMARY KEY,
name text      NOT NULL
);
COMMENT ON TABLE authors IS
'Keeps authors.
Contains id and name.';
```
**Previous behavior:** The code generator (`sqlc generate`) exited with an error:
```
...
// Keeps authors.
Contains id and name.
type Author struct {
ID int64 
Name string 
}
error generating code: source error: 17:1: expected declaration, found Contains
```
The reason is obvious: The code generator adds `//` only at the beginning of the comment string. As a result, only the first line of the comment string is commented out.
**New behavior:** Code generator adds `//` at the beginning of every line of the comment string. …
=> Support multi-line SQL comments

README.md
The example had invalid yaml syntax.
Removed the comma at the end of the line to make the example valid yaml.
=> Fix settings example in readme

internal/cmd/cmd.go
This is an easy way to know if you're on an unreleased version
=> cmd: Return next bug fix version

internal/endtoend/endtoend_test.go
"go vet" warns about this, presumably because a Fatal directive is not
catchable or re-throwable.
=> internal/endtoend: remove %w

README.md
=> README: Add section on running tests

internal/endtoend/testdata/named_param/go/query.sql.go, internal/endtoend/testdata/named_param/query.sql, internal/postgresql/ast/astutil.go
=> astutils: Apply changes to the ValuesList slice

Makefile, internal/catalog/build.go, internal/dolphin/parse.go, internal/endtoend/testdata/experimental_dolphin/go/models.go, internal/endtoend/testdata/experimental_dolphin/query.sql, internal/endtoend/testdata/experimental_dolphin/sqlc.json, internal/endtoend/testdata/experimental_elephant/go/models.go, internal/endtoend/testdata/experimental_elephant/query.sql, internal/endtoend/testdata/experimental_elephant/sqlc.json, internal/endtoend/testdata/experimental_lemon/go/models.go, internal/endtoend/testdata/experimental_lemon/query.sql, internal/endtoend/testdata/experimental_lemon/sqlc.json, internal/postgresql/parse.go, internal/postgresql/utils.go, internal/sql/ast/ast.go, internal/sql/catalog/catalog.go, internal/sqlite/listener.go, internal/sqlite/utils.go
Port ALTER TABLE support from `internal/catalog` to `internal/sql/catalog`. Add support for MySQL and SQLite. A note that SQLite does not support DROP COLUMN or ADD COLUMN IF EXISTS.
=> ast: Add AST for ALTER TABLE ADD / DROP COLUMN

internal/compiler/compile.go, internal/compiler/result.go, internal/endtoend/testdata/experimental_elephant/go/models.go, internal/endtoend/testdata/experimental_elephant/query.sql, internal/postgresql/parse.go, internal/sql/ast/ast.go, internal/sql/catalog/catalog.go
MySQL and SQLite do not support CREATE TYPE ... ENUM, so this change
mainly involves porting the existing enum support from the dinosql /
catalog package to the sql/catalog package
=> ast: Add support for CREATE TYPE as ENUM

internal/sql/catalog/catalog.go, internal/sql/errors/errors.go
Unlike the errors defined in pg/errors.go, these should play nicely with
errors.As and errors.Is
=> sql/errors: Add a new errors package

internal/postgresql/catalog_test.go, internal/postgresql/parse.go, internal/sql/ast/ast.go, internal/sql/catalog/catalog.go, internal/sql/catalog/func.go, internal/sql/errors/errors.go
This is more than a port, as the existing functionality in `internal/catalog` was buggy and incomplete.
=> Implement CREATE / DROP FUNCTION

README.md
While there, don't terminate a list item with a full stop ('.').
=> Move hyphen-minus to the right place

internal/catalog/build.go, internal/catalog/build_test.go, internal/postgresql/catalog_test.go, internal/postgresql/parse.go, internal/sql/ast/ast.go, internal/sql/catalog/catalog.go, internal/sql/catalog/types.go
This pull requests actually includes two parallel implementations of ALTER TYPE, one for the legacy `internal/catalog` package, and one for the new `internal/sql/catalog` package. I really need to port the `internal/dinosql` package over to the new catalog so I don't need to waste time doing things twice.
Fix #428
=> Implement ALTER TYPE RENAME VALUE / ADD VALUE

examples/authors/db_test.go, examples/booktest/postgresql/db_test.go, examples/ondeck/db_test.go, go.sum, internal/cmd/generate.go, internal/compiler/compile.go, internal/config/config.go, internal/config/v_one.go, internal/dinosql/parser.go, internal/mysql/parse.go, internal/sqltest/postgres.go
This adds support for passing in a list of files or directories for queries and schemas.
This came about because the project currently recommends workarounds for SQL views, where users create a table definition that is the would-be table schema for the view. We did not want this file living alongside our production schema so I created an adjacent director called `workarounds`, this was going to make scripting fresh DB migrations much simpler as I did not have to regex out workaround files. However, because I could only pass in one path this did not work. This adds that support.
It is kind of massive and breaks config backwards compatibility but I can look into options for fixing that.
=> A list of paths can be past in for schemas and queries

internal/dinosql/parser.go, internal/dinosql/parser_test.go
When setting schema to a directory (i.e. `./migrations`), sqlc wasn't excluding `*.down.sql` and was getting tripped up. This PR has a test+fix for this issue.
Thanks for all the great work!
=> exclude golang-migrate .down.sql files in dirs + single files

Makefile, README.md
Add sqlc-dev as a dependency of the "regen" target to lower the
possibility that someone is running regenerate with an out of date
sqlc binary.
Also update the docs to refer to the Make target instead of the
script.
=> Makefile: update target

internal/config/config.go, internal/config/v_one.go, internal/dinosql/gen.go, internal/dinosql/kotlin/gen.go, internal/mysql/gen.go
If set to true, the struct names are not singularized.
My table names are not English, stripping the "s" from the end
is quite annoying.
=> Add LeavePlural config option

internal/dinosql/parser.go, internal/endtoend/testdata/invalid_params/query.sql
A invalid query with mixed parameter styles ($1, sqlc.arg, @) and
missing parameter refs ($1, $3, but no $2) should error with a mixed
parameter style error.
Before this change, this query fail to compile with an ambiguous `could not determine data type of parameter $2` message.
Thanks to @kevinburkemeter for the bug report.
=> internal/dinosql: Check parameter style before ref

internal/postgresql/ast/astutil.go
The Arg field was incorrectly named "Args" in the call to apply.
Credit to @kevinburkemeter for the initial bug report
=> internal/postgresql: Fix NamedArgExpr rewrite

internal/cmd/cmd.go, internal/endtoend/endtoend_test.go
The parser seems to be in a good enough state to turn on my default. Setting `SQLC_EXPERIMENTAL_PARSER=off` will revert to previous behavior. The plan is to remove the old code path in the v1.5.0 release.
=> compiler: Enable experimental parser by default

internal/endtoend/endtoend_test.go
Create a per-test configuration file. Currently it's only used to disable the deprecated parser for new tests. Add a `endtoend.json` file in an directory inside `internal/endtoend/testdata/*`.
```
{
"experimental_parser_only": true
}
```
=> endtoend: Add per-test configuration files

internal/endtoend/endtoend_test.go, internal/endtoend/testdata/invalid_func_args/query.sql, internal/endtoend/testdata/invalid_func_args/stderr.txt, internal/endtoend/testdata/invalid_params/query.sql, internal/endtoend/testdata/invalid_params/stderr.txt, internal/endtoend/testdata/invalid_queries_bar/query.sql, internal/endtoend/testdata/invalid_queries_bar/stderr.txt, internal/endtoend/testdata/invalid_queries_foo/query.sql, internal/endtoend/testdata/invalid_queries_foo/stderr.txt, internal/endtoend/testdata/missing_semicolon/query.sql, internal/endtoend/testdata/missing_semicolon/stderr.txt, internal/endtoend/testdata/mysql_errors/query.sql, internal/endtoend/testdata/mysql_errors/stderr.txt
The existing setup didn't work well when testing groups of SQL files.
=> endtoend: Read expected stderr failures from disk

internal/endtoend/testdata/mysql_param/go/query.sql.go, internal/endtoend/testdata/mysql_param/query.sql, internal/mysql/param.go
The sqlc MySQL parser didn't have the logic to handle a where clause with parenthesis in it and would panic. This seems to fix it, but there might be some edge cases I didn't account for. (Sorry for the semi-contrived test case, its similar to what I needed but its also kinda silly)
=> MySQL: Prevent Panic when WHERE clause contains parenthesis. 

Dockerfile
This only affects the sqlc Docker container
=> docker: Build sqlc using Go 1.14

internal/codegen/golang/gen.go, internal/config/config.go
sqlc is very useful when creating REST APIs. However when querying for a collection of models using the `:many` query, while the corresponding database table is empty, the result in JSON is marshalled into `null`. To improve the usability with APIs returning JSON and preferabily `[]` instead of `null`, I propose to add an option to change the returned slice of generated `:many` queries. See examples below.
Let's take a look at the example in `sqlc/examples/authors/`:
The following query in `query.sql`:
```sql
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;
```
Generates the following Go code:
```go
func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
// snip ...
var items []Author
// snip ...
return items, nil
}
```
When the database table `authors` is …
=> Add option to return empty slices in generated :many query, to improve usability with JSON

go.mod, internal/cmd/generate.go, internal/compiler/compile.go, internal/compiler/parse.go, internal/debug/dump.go, internal/opts/debug.go, internal/opts/parser.go
The SQLCDEBUG environment variable can be used to control dumping AST
nodes to stdout.
=> cmd: Add debugging support

internal/codegen/golang/postgresql_type.go, internal/endtoend/testdata/datatype/go/models.go, internal/endtoend/testdata/datatype/sql/numeric.sql
=> golang: Generate correct types for int2 and int8

internal/codegen/golang/gen.go
`:execresult` is generating with an extra `:=` in the return. This just removes those two characters.
=> Fixed :execresult generation

internal/endtoend/endtoend_test.go
otherwise it will grow without bound
=> reset stderr between benchmark runs

README.md
Fixed misspelling of `emit_empty_slices` as `emit_emptly_slices`.
=> Fixed typo in settings example in README

internal/endtoend/testdata/ddl_create_func_exists/query.sql, internal/endtoend/testdata/ddl_create_func_exists/sqlc.json, internal/endtoend/testdata/ddl_create_func_exists/stderr.txt, internal/sql/catalog/catalog.go
=> sql/catalog: Fix comparison of pg_catalog types

internal/engine/dolphin/convert.go
We don't currently process create view statements, but drop view statements get
parsed as regular drop statements, so we need to skip processing drops when
they're for views.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kyleconroy/sqlc/653)
=> Dolphin: Skip processing view drops

Makefile, README.md, docker-compose.yml
Use Docker Compose to run MySQL and PostgreSQL locally
=> Support running examples tests locally

internal/codegen/golang/mysql_type.go, internal/endtoend/testdata/insert_select/mysql/go/models.go, internal/endtoend/testdata/insert_select/mysql/go/query.sql.go
Fixes #666 
Please see the discussion on https://github.com/go-sql-driver/mysql/issues/440 as to why we can't default to using tinyint as a bool value.
=> dolphin: Represent tinyint as int32

internal/engine/dolphin/stdlib.go
Slowly add function signatures for the MySQL standard library. Since sqlc doesn't yet contemplate types correctly, it's more important to get the return value and number of arguments correct.
Fixes #657
=> dolphin: Add function signatures

internal/endtoend/testdata/params_duplicate/mysql/go/models.go, internal/endtoend/testdata/params_duplicate/mysql/go/query.sql.go, internal/endtoend/testdata/params_duplicate/mysql/query.sql, internal/endtoend/testdata/params_duplicate/mysql/schema.sql, internal/sql/rewrite/parameters.go
While this technically is a solution for #777, I'm not happy with it. I'd like to get real support for named parameters before I release 1.6.0.
=> Generate valid code for MySQL named parameters

README.md
`internal/dinosql/gen.go` was already missing and the link led to a 404 page, so I fixed it. to `internal/codegen/golang/postgresql_type.go`
#751
=> 📝  fix readme supported types file link

README.md
sqlc can now be installed on MacOS via brew without a tap!
=> brew install sqlc

README.md
`emit_db_tags` option has been implemented, but it was not mentioned anywhere in the documentation, so I added it.
=> docs: Update README.md for emit_db_tags

go.mod, internal/cmd/cmd.go, internal/cmd/generate.go, internal/endtoend/endtoend_test.go
You can now pass the `--file` flag (`-f` for short) to the `init`, `generate` and `compile` commands.
The paths inside the configuration file are relative to the directory that file is in.
Fixes #825
=> cmd: Allow config file location to be specified

internal/cmd/cmd.go
Only use the flag value if it was changed by the user. Ignore the default value of empty string
Fixes #864
=> Check if the flag was changed

internal/cmd/generate.go
```bash
$ sqlc-dev generate
query.sql:2:10: syntax error near "SELECTTTT dayname(?);" "
$ echo $?
1
```
Fixes #869
=> Exit with non-zero error code when parsing fails

.github/workflows/equinox.yml, internal/engine/postgresql/convert.go, internal/engine/postgresql/parse.go, internal/engine/postgresql/parse_windows.go, internal/engine/postgresql/utils.go
The PostgreSQL parser we use does not support Windows. However, the MySQL parser does. Update the `engine/postgresql` package to build on Windows. This version of the PostgreSQL parser always returns an error.
=> Initial Windows support

internal/engine/dolphin/stdlib.go
So the mysql timestampdiff documentation does not explicitly declare the
return type, but the documentation heavily implies int.
On the other hand, the MariaDB documentation explicitly specifies it as
int, so we're going to run with int.
=> Make timestampdiff return int.

internal/cmd/cmd.go, internal/cmd/generate.go, internal/endtoend/endtoend_test.go
Put Python support behind the experimental flag. New languages and databases will go behind the flag until their implementation is stable.
cc @robholt
=> cmd: Add the --experimental flag

internal/compiler/output_columns.go, internal/compiler/resolve.go, internal/endtoend/testdata/data_type_boolean/mysql/db/query.sql.go, internal/endtoend/testdata/insert_select/mysql/go/query.sql.go
Since MySQL doesn't have native boolean support, we turn all values with data type `tinyint(1)` into bools. We need to have the associated length with the datatype for this to work. Make sure that we pass length in all the required spots.
Fixes #856
=> Correctly generate code for MySQL cool

internal/engine/dolphin/stdlib.go
Added support for the mysql function LAST_INSERT_ID with an expression.
Now this query leads to an error `function last_insert_id(unknown) does not exist`
```
INSERT INTO foo (id)
VALUES (LAST_INSERT_ID(UUID_SHORT()))
```
=> Calling mysql function LAST_INSERT_ID(expr)

docs/howto/select.md
I spent quite a time figuring this one out because it's not mentioned in the documentation that we have to pass postgres data types. I was using
```
ANY(sqlc.arg(roles)::string[])
```
which is supposed to be 
```
ANY(sqlc.arg(roles)::varchar[]).
```
=> Documentation on slice as parameter to a query

internal/compiler/output_columns.go, internal/endtoend/testdata/func_return/go/query.sql.go, internal/endtoend/testdata/func_return/query.sql
=> Skip over unknown functions in source tables

docs/reference/config.md
Added some details on the documentation regarding the feature developed in #998.
=> docs: add docs for the feature added in #998

docs/howto/select.md
This is very minor, but may confuse newcomers.
=> Fix typos in howto/select generated code sample

docker-compose.yml
The right way to configure the *root* password is using the environment variable
`MYSQL_ROOT_PASSWORD`.
It also remove the `MYSQL_PASSWORD` because is only used the root user.
From MySQL log:
```
2021-08-13 20:28:55+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2021-08-13 20:28:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.26-1debian10 started.
2021-08-13 20:28:55+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
Remove MYSQL_USER="root" and use one of the following to control the root user password:
- MYSQL_ROOT_PASSWORD
- MYSQL_ALLOW_EMPTY_PASSWORD
- MYSQL_RANDOM_ROOT_PASSWORD
```
=> Remove MYSQL_USER and MYSQL_PASSWORD from docker-compose.yaml

internal/codegen/golang/go_type.go, internal/codegen/golang/imports.go, internal/codegen/golang/postgresql_type.go
Refactor import logic into a two shared functions instead of three
confusing call sites.
=> codegen/golang: Consolidate import logic

internal/codegen/golang/imports.go, internal/codegen/golang/postgresql_type.go, internal/endtoend/testdata/json/postgresql/pgx/go/models.go, internal/endtoend/testdata/json/postgresql/stdlib/go/models.go, internal/endtoend/testdata/json_build/postgresql/pgx/go/query.sql.go
lib/pq: For nullable values, use pqtype.NullRawMessage
pgx/v4: Always use pgtype.JSON[B]
Fixes #129 
Fixes #909
=> Handle null PostgreSQL JSON values

internal/codegen/golang/imports.go, internal/codegen/golang/postgresql_type.go, internal/endtoend/testdata/datatype/pgx/go/models.go, internal/endtoend/testdata/datatype/pgx/sql/rangetypes.sql, internal/endtoend/testdata/datatype/stdlib/go/models.go, internal/endtoend/testdata/datatype/stdlib/sql/rangetypes.sql
Support all six built-in range types:
* int4range — Range of integer
* int8range — Range of bigint
* numrange — Range of numeric
* tsrange — Range of timestamp without time zone
* tstzrange — Range of timestamp with time zone
* daterange — Range of date
Fixes #323
=> codegen/golang: Add pgx support for range types

docs/reference/language-support.rst
=> docs: Fix invalid language support table

docs/index.rst, docs/tutorials/getting-started-mysql.md, docs/tutorials/getting-started-postgresql.md
=> docs: Add a getting started guide for MySQL

internal/cmd/cmd.go, internal/cmd/generate.go, internal/compiler/compile.go, internal/endtoend/endtoend_test.go, internal/engine/dolphin/parse.go, internal/engine/postgresql/parse.go, internal/engine/sqlite/parse.go, internal/sql/sqlpath/read.go, internal/sqltest/mysql.go, internal/sqltest/postgres.go, internal/tools/sqlc-pg-gen/main.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
No breaking changes.
=> refactor: move from io/ioutil to io and os package

docs/overview/install.md
=> docs: Replace deprecated go get with go install

internal/endtoend/testdata/json_build/postgresql/pgx/go/query.sql.go, internal/endtoend/testdata/json_build/postgresql/pgx/query.sql, internal/endtoend/testdata/json_build/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/json_build/postgresql/stdlib/query.sql, internal/engine/postgresql/pg_catalog.go
Update the function signature of jsonb_build_object and
jsonb_build_array with variadic arguments.
Fixes #1210
=> fix(engine/postgresql): jsonb_build_object

docs/overview/install.md
Add go 1.17+ install intructions, `go get` has been deprecated
from go 1.17 and onwards as an install method.
=> docs: add go.17+ install instructions

docs/howto/ddl.md
=> docs: warn about golang-migrate file order

docs/conf.py, docs/overview/install.md
Update download links to point to v1.11.0
=> docs: Bump version to 1.11.0

go.mod, internal/codegen/golang/postgresql_type.go, internal/endtoend/testdata/datatype/pgx/go/models.go, internal/endtoend/testdata/datatype/stdlib/go/models.go, internal/endtoend/testdata/json_tags/camel_case/postgresql/pgx/go/models.go, internal/endtoend/testdata/json_tags/camel_case/postgresql/stdlib/go/models.go, internal/endtoend/testdata/json_tags/pascal_case/postgresql/pgx/go/models.go, internal/endtoend/testdata/json_tags/pascal_case/postgresql/stdlib/go/models.go, internal/endtoend/testdata/json_tags/snake_case/postgresql/pgx/go/models.go, internal/endtoend/testdata/json_tags/snake_case/postgresql/stdlib/go/models.go
Go added support for sql.NullInt16 in the standard library as of go1.17 (https://github.com/golang/go/issues/40082), so sqlc can now use the appropriate nullable type for int16.
=> feat(postgres): Add support for sql.NullInt16

docs/howto/select.md
=> Fixed typo in select.md

Makefile, examples/authors/mysql/db_test.go, examples/authors/postgresql/db_test.go, examples/booktest/postgresql/db_test.go, examples/ondeck/mysql/db_test.go, examples/ondeck/postgresql/db_test.go, internal/engine/postgresql/parse_windows.go, internal/engine/postgresql/utils.go
Make it easier to format code using `make fmt`.
=> build: Format all Go code

internal/compiler/parse.go, internal/compiler/resolve.go, internal/config/config.go, internal/config/v_one.go, internal/endtoend/testdata/strict_function_checks/postgresql/query.sql, internal/endtoend/testdata/strict_function_checks/postgresql/sqlc.json, internal/endtoend/testdata/strict_function_checks/postgresql/stderr.txt, internal/sql/validate/func_call.go
Fixes #537 
We need to add this behind a flag, otherwise it will break many people's build. To enable this, set `strict_function_checks` to `true`.
```
{
"version": "1",
"packages": [
{
"name": "querytest",
"path": "go",
"schema": "query.sql",
"queries": "query.sql",
"engine": "postgresql",
"strict_function_checks": true
}
]
}
```
=> fix: Enable strict function checking

internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/pgx/go/query.sql.go, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/pgx/query.sql, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/pgx/schema.sql, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/stdlib/query.sql, internal/endtoend/testdata/ddl_alter_table_set_schema/postgresql/stdlib/schema.sql, internal/sql/catalog/table.go
Once a table schema has been changes via `ALTER TABLE <name> SET SCHEMA <new_schema>`, any `UPDATE` queries do not recognise the new table name.
Example:
schema.sql
```sql
CREATE SCHEMA foo;
CREATE TABLE bar (name text);
ALTER TABLE bar SET SCHEMA foo;
```
queries.sql
```sql
-- name: UpdateFooBar :exec
UPDATE foo.bar SET name = $1;
```
The compiler does not recognise the `foo.bar` table and throws an error.
=> Bug: ALTER TABLE SET SCHEMA

docs/reference/config.md
The docs link to PG types to be used in overrides, but those include unusable options. For instance, `db_type: smallint` doesn't work, whereas `db_type: pg_catalog.int2` does.
This adds a note to tell the reader to use the `pg_catalog` types when available.
=> docs: Specify which db_type should be used in overrides

internal/codegen/golang/templates/pgx/copyfromCopy.tmpl, internal/endtoend/testdata/copyfrom/postgresql/pgx/go/copyfrom.go, internal/endtoend/testdata/copyfrom/postgresql/pgx/query.sql
The changes in #1417 fixed newline comments in all queries except for copyfrom.
This PR adds the same changes for copyfrom so generated comments do not have
a new line before the function.
Signed-off-by: Alex Dulin <alex@morningconsult.com>
=> chore: fix extra newline in comments for copyfrom

.github/workflows/ci.yml, Makefile
There are no tests, so don't run `go test`
Addresses https://github.com/kyleconroy/sqlc/pull/1488
=> build(endtoend): Don't run tests in testdata

docs/howto/update.md
=> docs: Add more examples to updating rows

docs/reference/language-support.rst, internal/cmd/generate.go
The use of the `--experimental` flag is no longer required
=> feat(python): Graduate Python support to beta

docs/overview/install.md
For running sqlc with docker on windows cmd, instead of specifying the root folder with `pwd` , it should be specified with `cd` on documentation.
=> feat: run sqlc with docker on windows cmd

internal/codegen/golang/struct.go
This situation can occur if the column name starts with an underscore prefix and the following character is a digit:
```
create table thing (
_1099Form text
);
```
currently the generator would balk because  the generated struct would be :
```
type Thing struct {
1099Form string
}
```
and `1099Form` is not a valid name (it starts with a digit).
with this change we would instead get instead:
```
type Thing struct {
_1099Form string
}
```
=> Prepend an underscore to a StructName if it starts with a digit.

docs/howto/named_parameters.md
I [tried](https://github.com/kyleconroy/sqlc/pull/1579) to add `sqlc.narg` to the examples folders too, but failed on the Kotlin code generator.  I am isolating the documentation here to make it easier to merge.
=> docs: add documentation for sqlc.narg()

docs/howto/transactions.md
As asked by https://github.com/kyleconroy/sqlc/discussions/1479
=> docs: Add some more example code for running transactions

docs/howto/insert.md, docs/howto/transactions.md, docs/reference/query-annotations.md
1. format all of the example code
2. fix a compile error
ref: #1261
=> docs: fix examples

internal/cmd/cmd.go
If you call cmd.Do programmatically more than once, it panics on the 2nd run due to this error:
```
panic: upload flag redefined: dry-run
goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0005b1300, 0xc0001243c0)
external/com_github_spf13_pflag/flag.go:848 +0x825
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0005b1300, 0x5122970, 0xc0005cef19, 0x4e6bd3d, 0x7, 0x0, 0x0, 0x4e9006b, 0x24, 0xc0005cef19)
external/com_github_spf13_pflag/flag.go:831 +0x10b
github.com/spf13/pflag.(*FlagSet).BoolVarP(0xc0005b1300, 0xc0005cef19, 0x4e6bd3d, 0x7, 0x0, 0x0, 0x0, 0x4e9006b, 0x24)
external/com_github_spf13_pflag/bool.go:55 +0x97
github.com/spf13/pflag.(*FlagSet).BoolP(...)
external/com_github_spf13_pflag/bool.go:80
github.com/kyleconroy/sqlc/internal/cmd.Do(0xc00003c210, 0x0, 0x0, …
```
=> Fix panic when calling cmd.Do subsequently

docs/reference/config.md
`go_type` is an object, not sequence
=> doc: typo fix in overrides config example

internal/codegen/golang/imports.go, internal/endtoend/testdata/copyfrom_imports/postgresql/pgx/go/query.sql.go, internal/endtoend/testdata/copyfrom_imports/postgresql/pgx/query.sql
Depending on the commands used in your `query.sql` the `copyfrom.go`
may end up with unused package imports.
There is a patch for this problem that was merged in the #1386 PR.
However, it looks like some edge cases were left out of the fix.
This commit ensures that `buildImports` only has `copyfrom` queries
when called from `copyfromImports`.
=> [FIX] copyfrom imports

internal/endtoend/testdata/sqlc_arg_invalid/mysql/query.sql, internal/endtoend/testdata/sqlc_arg_invalid/mysql/stderr.txt, internal/endtoend/testdata/sqlc_arg_invalid/postgresql/query.sql, internal/endtoend/testdata/sqlc_arg_invalid/postgresql/stderr.txt, internal/sql/validate/func_call.go, internal/sql/validate/param_style.go
=> Validate sqlc function arguments

docs/howto/named_parameters.md
Fixed a typo in [naming parameters](https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters) doc page. Changed `sql.narg` to `sqlc.narg`.
=> fix: fixed typo `sql.narg` in doc

docs/guides/plugins.md, docs/index.rst, docs/reference/config.md, docs/reference/language-support.rst
Still need more, but this is a good first pass
=> docs: Add process-based plugin docs

docs/reference/config.md
=> Added documentation for type overriding and field renaming for the version 2 of the configuration file

internal/ext/wasm/wasm.go
Also change default file permissions
Fixes #1705
Fixes https://github.com/kyleconroy/sqlc/issues/1706
=> plugins(wasm): Change default cache location

internal/cmd/generate.go, internal/config/config.go, internal/endtoend/testdata/wasm_plugin_sqlc_gen_greeter/sqlc.json, internal/ext/wasm/wasm.go
Use sha256 to match Bazel's http_file directive. I was originally going to make these [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#using_subresource_integrity) values, but the spec allows for multiple space-separated values. The checksum is also base64-encoded, which means it can't be used a file name, as it may have a slash in it.
=> plugins(wasm): Change the SHA-256 config key

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, docker-compose.yml
* update devcontainer go image to 1.18-bullseye to match go.mod
* use [mysql/mysql-server](https://hub.docker.com/r/mysql/mysql-server/tags) image to support arm based machine like M1 Mac
* set `MYSQL_ROOT_HOST: '%'` to allow access from any host
* https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
* add `links` section to avoid DNS lookup failure
=> improve mysql container support for testing

internal/compiler/compile_test.go, internal/compiler/expand.go, internal/endtoend/testdata/select_star/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/select_star/postgresql/stdlib/schema.sql
If columns are created with CamelCase, they have to be quoted or else
postgres won't find them.
This PR only applies to ```SELECT * FROM tablename``` queries. When the column names are specified individually with quotes, it already works.
fixes #1718
=> fix(postgresql): Add quotes for CamelCase columns

internal/codegen/golang/sqlite_type.go
To keep the API consistent with mysql
```go
case "blob", "binary", "varbinary", "tinyblob", "mediumblob", "longblob":
return "[]byte"
```
and postgres
```go
case "bytea", "blob", "pg_catalog.bytea":
return "[]byte"
```
I suggest sqlc uses []byte instead of []uint8. If the field is nullable, it is pointles to have a *[]uint8 (or *[]byte) because slices are already pointers, and a slice can be nil
=> sqlite - use []byte for blobs

internal/ext/wasm/wasm.go
Compiled modules can't be shared across wasmtime versions. Make sure to
include the current version of wasmtime in the module filename.
=> fix(wasm): Version modules by wasmtime version

internal/codegen/golang/imports.go
Fixes #1253 by checking for type needed for a given slice, this also allows passing slices to as parameters to queries such as [WHERE ANY](https://docs.sqlc.dev/en/stable/howto/select.html#passing-a-slice-as-a-parameter-to-a-query) without being restricted to postgres data types
=> fix: missing imports for slices

internal/ext/wasm/nowasm.go, internal/ext/wasm/wasm.go
I found an inconsistency between the implementation of the wasm and nowasm files.
I thought that since it seems that this feature can be disabled, it would be nice to be able to control it from a tag. So I added that too.
The reason I came about this in the first place was that it seems that there is a Rust dependency in the wasm implementation, and that conflicts with my build system. I'm sure I could figure it out if this will not be possible in the future.
=> Add nowasm tag, fix nowasm inconsistency

.devcontainer/Dockerfile, .devcontainer/docker-compose.yml, .github/workflows/ci.yml, examples/batch/postgresql/batch.go, go.mod, internal/codegen/golang/templates/template.tmpl, internal/endtoend/testdata/batch/postgresql/pgx/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/go/batch.go
Go 1.19 isn't required as 1.18 will still be supported for the time being.
=> build: Upgrade to Go 1.19

docs/guides/plugins.md, docs/reference/changelog.md
Also add a first-pass at WASM codegen docs
=> docs: Add 1.15 changelog

docs/index.rst, docs/tutorials/getting-started-sqlite.md
SQLite support is fire!
Add SQLite guide document created from postgresql guide
=> docs: Add a getting started guide for SQLite

internal/endtoend/testdata/valid_group_by_reference/postgresql/go/query.sql.go, internal/engine/postgresql/contrib/adminpack.go, internal/engine/postgresql/contrib/citext.go, internal/engine/postgresql/contrib/cube.go, internal/engine/postgresql/contrib/dblink.go, internal/engine/postgresql/contrib/fuzzystrmatch.go, internal/engine/postgresql/contrib/hstore.go, internal/engine/postgresql/contrib/intarray.go, internal/engine/postgresql/contrib/isn.go, internal/engine/postgresql/contrib/ltree.go, internal/engine/postgresql/contrib/pageinspect.go, internal/engine/postgresql/contrib/pg_stat_statements.go, internal/engine/postgresql/contrib/pg_visibility.go, internal/engine/postgresql/contrib/pgcrypto.go, internal/engine/postgresql/contrib/pgrowlocks.go, internal/engine/postgresql/contrib/pgstattuple.go, internal/engine/postgresql/contrib/sslinfo.go, internal/engine/postgresql/contrib/tablefunc.go, internal/engine/postgresql/contrib/xml2.go, internal/engine/postgresql/extension.go, internal/engine/postgresql/pg_catalog.go, internal/tools/sqlc-pg-gen/main.go
This is sort of a yak-shaving task for https://github.com/kyleconroy/sqlc/pull/1748
Problem: there seem to have been some manual edits to pg_catalog.go over the course of time.  This makes it hard (almost impossible actually) to do any change there with any confidence.
Solution: Do some detective work on the manual edits performed, and incorporate them into pg-gen.  Once that is done the work on #1748 will be a lot easier.
Here are the 2 manual edits as far as I can tell:
https://github.com/kyleconroy/sqlc/commit/95131550616d8d06c9a484e948e91a6a7ed7b3cc (pg_catalog functions with variadic signatures - this is completely solved by this PR)
And
https://github.com/kyleconroy/sqlc/commit/846c6298ca0a53ab0cf176d16b4da56c52345d3c (manual edits to pg_catalog that I _believe_ will be fixed "right …
=> pg-gen: make sqlc-pg-gen the complete source of truth for pg_catalog.go

internal/compiler/output_columns.go, internal/endtoend/testdata/coalesce/postgresql/pgx/go/query.sql.go, internal/endtoend/testdata/coalesce/postgresql/stdlib/go/query.sql.go
This change follows the previous implementation that mutates and returns the first column, but switches only the `.NotNull` value depending on the situation.
- Is it sufficient that asserting only types of columns and constants?
- Also I'm concerned that the `A_Const` node may contain `Null`.
Also, I am new to Golang OSS, so I may be making some large mistakes. Thank you in advance for your review.
BREAKING CHANGE: 🧨 `coalesce()` may assign nullable results
✅ Closes: #1663
=> fix: 🐛 Correctly switch `coalesce()` result `.NotNull` value

examples/batch/postgresql/batch.go, examples/batch/postgresql/db_test.go, internal/codegen/golang/imports.go, internal/codegen/golang/templates/pgx/batchCode.tmpl, internal/endtoend/testdata/batch/postgresql/pgx/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/go/batch.go
Because the batch queries are only being closed when checking for 2 errors (batch results closed or no result), other errors cause the generated code to infinite loop. This changes from a for loop that only breaks on checking the errors to a for loop that also considers the the total number of params passed in.
Some errors will not infinite loop if you close the results yourself. However, there are other errors that you can't close --
* Context cancelled during a batch query
* Connection is busy
* Bad query
Bad queries typically happen in tests, but the infinite loop has eaten up >20Gb of RAM within a few minutes for me before.
This is usually what happens. It infinite loops, so I can't interrupt the process, and then I have to do `ps aux | grep <>` to find and kill the process manually: …
=> fix: prevent batch infinite loop with arg length

internal/cmd/generate.go, internal/config/config.go
Currently when use version "3" for testing, it returns:
```
The configuration file has an invalid version number.
The only supported version is "1".
```
while `version "2"` is also supported.
=> fix: version support in error message

examples/batch/postgresql/batch.go, examples/batch/postgresql/models.go, examples/batch/postgresql/querier.go, examples/batch/postgresql/query.sql, examples/batch/postgresql/query.sql.go, examples/batch/postgresql/schema.sql, internal/codegen/golang/imports.go, internal/codegen/golang/query.go
The original code was using all queries to build the batch imports, so the `batch.go` file was including extraneous imports that were not needed.
And also include batch cmd commands as having return types, which was preventing the build imports code for batch queries to never return true for return types.
Fixes #1682
Fixes #1792
=> fix: batch imports filter queries, update cmds having ret type

examples/batch/postgresql/batch.go, examples/batch/postgresql/querier.go, examples/batch/postgresql/query.sql, internal/compiler/parse.go, internal/sql/validate/cmd.go
The batch validation code was only allowing numbered params contribute to the total parameter count of a query, which prevented batch queries with only named parameters from successfully generating code.
Fixes #1625
=> fix: named params contribute to batch parameter count

docs/howto/ddl.md, docs/reference/config.md, docs/tutorials/getting-started-postgresql.md
Various documentation improvements.
- Be explicit that sqlc does not perform migrations, but rather parses the up migrations and ignores the down migrations.
- Update the configuration reference to link to the `gen` key.
- Updated the PostgreSQL getting started documentation to use version 2 of the configuration.
=> docs: various readability improvements

docs/reference/config.md
Hi all,
I believe the value of the db_type key in the config.md should be changed from "timestampz" to "timestamptz".
Thanks for creating this awesome package 🙂
=> Fix a typo in config.md

docs/tutorials/getting-started-sqlite.md
Firstly, thanks for the great project.
According to [the sqlite documentation](https://www.sqlite.org/autoinc.html), the `AUTOINCREMENT` keyword shouldn't be used in normal cases:
> The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. **It is usually not needed**.
> On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. **This is true regardless of whether or not the AUTOINCREMENT keyword is used**.
=> Remove unnecessary `AUTOINCREMENT` from example

internal/cmd/generate.go, internal/codegen/kotlin/gen.go, internal/compiler/parse.go, internal/opts/parser.go
`UsePositionalParameters` was only used by the Kotlin codegen package. Re-implement that logic inside Kotlin codegen without the compiler knowing about it.
=> compiler: Move Kotlin parameter logic into codegen

go.mod, go.sum
Amongst other improvements, this fixes build problems on macOS caused by the recent XCode 14.1 release, see
https://github.com/pganalyze/pg_query/issues/263 and https://github.com/postgres/postgres/commit/bc7a40b42eef717026d29b687157cd0af5adaadb.
=> Update pg_query_go to 2.2.0 / libpg_query to 13-2.2.0

.github/workflows/gen.yml, internal/tools/sqlc-pg-gen/main.go
The output of sqlc-pg-gen is difficult to reproduce when run in an inconsistent environment. Add a GitHub workflow to generate the code using a consistent OS (Ubuntu) and PostgreSQL version.
=> build: Run sqlc-pg-gen via GitHub Actions

internal/tools/sqlc-pg-gen/main.go
This fixes the compile/debug problem.
I need help re-generating pg_catalog.go etc. because when I call sqlc-pg-gen on my machine, the resulting file is a bit shorter and at least one endtoend test fails.
Refs: #1849
=> fix: initialize generated code outside function

Makefile, internal/cmd/cmd.go, internal/cmd/diff.go, internal/cmd/generate.go, internal/codegen/golang/result.go, internal/codegen/golang/struct.go, internal/codegen/json/gen.go, internal/debug/dump.go, internal/tracer/trace.go
Howdy!
In the course of learning this code, I found a few tiny changes
that I hope you might find useful! I'm happy to split these into
separate pull requests. Or, please feel free to close this if you
don't want drive-by changes like these.
Thank you!
---
- internal/cmd: fix an exit code buglet
It seems the previous code intended to interpret the error from
rootCmd.ExecuteContext() as an *exec.ExitError. That's not the way
it worked in practice, though. Instead, the typecheck on
err.(*exec.ExitError) used the error from the call to tracer.Start().
This is due to the scoping rules of if statements.
With this commit, cmd.Do() now attempts to interpret the command
execution error as an *exec.ExitError. It also prints the error
message to stderr, since the caller in ./cmd/sqlc.main doesn't …
=> *: clean up some tiny things

docs/reference/datatypes.md
Add's some extra notes around using UUID's with MySQL and how to automatically type the field to `uuid.UUID`.
=> update uuid docs for mysql

internal/endtoend/testdata/inflection/mysql/go/models.go, internal/endtoend/testdata/inflection/mysql/go/query.sql.go, internal/endtoend/testdata/inflection/mysql/query.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v4/go/models.go, internal/endtoend/testdata/inflection/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/inflection/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/inflection/postgresql/stdlib/go/models.go, internal/endtoend/testdata/inflection/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/stdlib/query.sql, internal/endtoend/testdata/inflection/sqlite/go/models.go, internal/endtoend/testdata/inflection/sqlite/go/query.sql.go, internal/endtoend/testdata/inflection/sqlite/query.sql, internal/inflection/singular.go
=>  Manual fix for incorrect handling of "calories"

docs/howto/delete.md, docs/howto/insert.md, docs/howto/prepared_query.md, docs/howto/update.md
Some of the sample code in "HOW-TO GUIDES" was outdated and has been updated.
`ExecContext()` signatures, for example.
=> docs: Update samples for HOW-TO GUIDES

go.mod, go.sum, internal/cmd/cmd.go, internal/cmd/generate.go, internal/ext/wasm/wasm.go
Use `errgroup` to parallelize generating code for each SQL package. For configurations with many packages, this should dramatically speed up generation.
=> cmd: Generate packages in parallel

internal/pattern/match.go
Type overrides are checked linearly for every codegen'd type reference. That linear check currently compiles a regexp pattern for every override that's considered (multiple times, actually). This commit adds a simple memoizing cache so that each pattern is only ever compiled once. This dramatically improves performance of sqlc for users who have many overrides. ngrok's usage of sqlc generate sees a 10x speedup from this change (4s -> 0.4s).
I haven't profiled the memory tradeoff here but I expect it's negligible.
=> internal/codegen: cache pattern matching compilations

docs/howto/insert.md
As mentioned fix of documentation for returning columns from inserted rows 
Refs #1589
=> fix: Documentation for returning columns from inserted rows

docs/reference/datatypes.md
Changed documentation for JSON-related data as if we go by the previously mentioned docs we won't be able to use fully qualified names in golang.
=> Changed documentation for json datatype.

internal/engine/postgresql/convert.go, internal/engine/postgresql/parse.go, internal/engine/postgresql/parse_disabled.go, internal/engine/postgresql/utils.go
Fixes #2050
postgresql parser requires cgo to build the native parser library, which can cause build issues such as #1956. Currently there is no way to disable support when it is not needed and the build issues can cause a problem. With this change, `CGO_ENABLED=0` can be used to work with the other parsers and avoid build issues.
=> Only enable postgresql support when cgo is enabled as it is required

.github/workflows/ci.yml
Turns out that https://github.com/kyleconroy/sqlc/pull/2075 caused all PRs from forks to fail.
=> ci: Only report test results on main

internal/config/config_test.go, internal/config/go_type.go
Remove an unnecessary validation check when processing type overrides for Go types. Fixes https://github.com/kyleconroy/sqlc/issues/2073
=> Fix for issue #2073

docs/guides/migrating-to-sqlc-gen-python.md
The yaml formatting under **Add the sqlc-gen-python plugin** is not accurate. Need to add the "-" to turn in into a list of dicts.
=> Updated the yaml formatting in the first section

internal/codegen/golang/go_type.go, internal/endtoend/testdata/any/pgx/v5/go/query.sql.go, internal/endtoend/testdata/array_text/pgx/v5/go/models.go, internal/endtoend/testdata/array_text/pgx/v5/go/query.sql.go, internal/endtoend/testdata/array_text_join/pgx/v5/go/models.go, internal/endtoend/testdata/array_text_join/pgx/v5/go/query.sql.go, internal/endtoend/testdata/ddl_alter_table_alter_type/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/exec_imports/pgx/v5/go/models.go, internal/endtoend/testdata/overrides/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/select_text_array/pgx/v5/go/query.sql.go, internal/endtoend/testdata/unnest/postgresql/pgx/v5/go/querier.go, internal/endtoend/testdata/unnest/postgresql/pgx/v5/go/query.sql.go
=> Remove direct use of pgtype.Array with pgx/v5

internal/codegen/golang/mysql_type.go, internal/endtoend/testdata/datatype/mysql/go/models.go, internal/endtoend/testdata/valid_group_by_reference/mysql/go/models.go
add: [Generated code for float column in MySQL is of type interface{} instead of float64](https://github.com/kyleconroy/sqlc/issues/2095)
=> add: float support mysql

.devcontainer/Dockerfile, .github/workflows/ci.yml, .github/workflows/gen.yml, go.mod
Go 1.20 has now had a point release, so I'm comfortable updating all our tooling to use it.
=> Upgrade to Go 1.20

internal/endtoend/endtoend_test.go, internal/endtoend/testdata/process_plugin_sqlc_gen_json/exec.json
=> test: Skip tests if required plugins are missing

internal/sql/catalog/types.go
=> Enum ordering minor code tidy up

docs/reference/config.md
I noticed the sqlite option wasn't added to the configuration docs.
=> docs(config.md): add `sqlite` as engine option

README.md
I think this post has a lot of useful information, and people not familiar with sqlc will find it interesting.
=> Add link to introductory blog post

internal/cmd/cmd.go, internal/endtoend/endtoend_test.go
For backwards compatability, the flag still exists but is a no-op. If we need feature flagging in the future, we'll develop a more robust system than what this flag provided.
=> cmd/sqlc: Remove --experimental flag

internal/cmd/generate.go
Use filepath.Rel() when formatting filenames in stderr output, for consistency
=> More consistent filename formatting in codegen stderr output

docs/reference/config.md
I found this option in code, but not documented.
https://github.com/kyleconroy/sqlc/blob/20372d7579876f93e361d7fcda79364d638ec818/internal/config/go_type.go#L15-L15
=> docs: Add missed configuration option

docs/reference/environment-variables.md, internal/ext/wasm/wasm.go
If specified, use the given directory as the base for temporary folders. Only applies when using WASM-based codegen plugins.
=> bin/sqlc: Add SQLCTMPDIR environment variable

internal/inflection/singular.go
We hit a table where "waves" was singularized to "wafe". Probably caught the rule attempting to set "knives" -> "knife" and "wives" -> "wife".
=> fix: correct singularization of "waves"

internal/config/config.go, internal/config/v_two.go
When following the docs for renames for `pkg` scoped renames, the renames were not applying. This is my first look into the sqlc config, but it looked like things were just not plumbed through.
I just adds setting the renames from the yaml parse. In the combine settings I made sure to assign the renames from the pkg (the global was already set). This change does make pkg renames override global ones.
---
For unit testing, I noticed all the `endtoend/testdata` use a v1 config. Instead of adding more vectors to that to also do `v2` directories, what if we just added a `sqlc.v1.yaml` and `sqlc.v2.yaml` to each directory and run it twice? Or something of that nature to test v2 configs? At present this is not tested aside from some manual checking.
=> fix: Honor Package level renames in v2 yaml config

docs/howto/named_parameters.md
I got an error when I followed the documentation.
```
db/query/user.sql:49:1: query "UpdateUser" specifies parameter ":one" without containing a RETURNING clause
```
db/query/user.sql
```sql
-- name: UpdateUser :one
UPDATE users
SET
name = coalesce(sqlc.narg('name'), name),
email = coalesce(sqlc.narg('email'), email),
role = coalesce(sqlc.narg('role'), role),
bio = coalesce(sqlc.narg('bio'), bio),
hashed_password = coalesce(sqlc.narg('hashed_password'), hashed_password)
WHERE id = sqlc.arg('id');
```
I added RETURNING to avoid errors.
sqlc version
1.17.2
=> fix: `specifies parameter ":one" without containing a RETURNING clause`

internal/config/config.go, internal/config/v_one.go
Add organization, project and hostname options for future remote execution support.
=> config: Add top-level cloud configuration

internal/ext/wasm/wasm.go
As part of migrating Go plugins to the official Go toolchain from TinyGo, the wasmtime call pattern needed to be updated. This should be backwards compatible with TinyGo plugins.
=> ext/wasm: Check exit code on returned error

internal/cmd/generate.go, internal/remote/rpc.go
When not present in config, set default remote execution hostname to `remote.sqlc.dev`
=> Update default remote execution hostname

go.mod, go.sum, internal/endtoend/testdata/syntax_errors/postgresql/stderr.txt, internal/engine/postgresql/parse.go
Fixes issue #263
Recently pg_query_go began to return the full structured error info instead of just error message in https://github.com/pganalyze/pg_query_go/pull/76 which has released this functionality in [v4.2.1](https://github.com/pganalyze/pg_query_go/releases/tag/v4.2.1). This sqlc PR #2288 updates to use v4.2.1 for pg_query_go.
After that PR is merged, sqlc will still not correctly display the line and column numbers, as pg_query_go  `parser.Error` type has an `Error()` method that **only** includes the **message**, even though that same `parser.Error` type has all the other fields public.
**_This_** PR attempts to normalize the pg_query_go  `parser.Error` type  to a sqlc `*sqlerr.Error`.
+ Parse [here](https://github.com/pganalyze/pg_query_go/blob/main/parser/parser.go#LL106C15-L1 …
=> Feat: PostgreSQL capture correct line and column numbers for parse error

docs/reference/config.md, docs/reference/language-support.rst
Add removal notices to the configuration.
Add external links to the official plugins.
Replaces https://github.com/kyleconroy/sqlc/pull/2287
=> docs: Add F# community plugin

internal/endtoend/testdata/comment_on/postgresql/pgx/v4/go/models.go, internal/endtoend/testdata/comment_on/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/comment_on/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/comment_on/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/comment_on/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/comment_on/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/comment_on/postgresql/stdlib/go/models.go, internal/endtoend/testdata/comment_on/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/comment_on/postgresql/stdlib/query.sql, internal/engine/postgresql/parse.go, internal/sql/ast/comment_on_view_stmt.go, internal/sql/astutils/rewrite.go, internal/sql/astutils/walk.go, internal/sql/catalog/catalog.go, internal/sql/catalog/comment_on.go
=> feat: add supporting COMMENT ON VIEW

internal/codegen/golang/field.go, internal/codegen/golang/result.go, internal/endtoend/testdata/sqlc_embed/postgresql/pgx/go/query.sql.go
fix #2243 
Previously, SetCaseStyle was used only for column names (snake case), so the `toSnakeCase` function worked correctly with strings.ToLower only.
Convert the model name (camel case) to snake case to get the tag name used in `sqlc.embed`.
This breaks the precondition of the `toSnakeCase` function and it no longer works correctly.
So we fixed the `toSnakeCase` function to work correctly even if the input is camel case.
If the proposed fix approach is incorrect, please let me know and feel free to close this PR
=> fix: fix toSnakeCase to handle input in camel case format

internal/codegen/golang/postgresql_type.go, internal/endtoend/testdata/emit_pointers_for_null_types/pgx/v5/go/models.go
`emit_pointers_for_null_types` where not supported in pgx v5, I've add the support in this PR 
That was a very small fix :D
fix #1991
=> feat: add support for pgx/v5 emit_pointers_for_null_types flag

internal/endtoend/testdata/invalid_group_by_reference/sqlite/stderr.txt, internal/endtoend/testdata/invalid_table_alias/sqlite/stderr.txt, internal/engine/sqlite/convert.go
Sorry, #2250 will panic if Location is not set properly.
Fixed sqlite convert because many nodes don't have Location set properly.
=> fix(engine/sqlite): add location info to sqlite ast

internal/sql/catalog/table.go
For example, I created tables following:
create table example_a {
id integer not null,
name varchar(32),
};
create table example_b {} inherits (example_a);
create table example_c {} inherits (example_a, example_b);
and then sqlc generated golang struct for table example_c:
type ExampleC struct {
ID int32
Name string
ID int32
Name string
}
So I fixed this in this PR.
=> fix: resolve duplicate fields generated when inheriting multiple tables

internal/endtoend/testdata/ddl_create_table_inherits/postgresql/pgx/v4/go/models.go, internal/endtoend/testdata/ddl_create_table_inherits/postgresql/pgx/v4/schema.sql, internal/endtoend/testdata/ddl_create_table_inherits/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/ddl_create_table_inherits/postgresql/pgx/v5/schema.sql, internal/endtoend/testdata/ddl_create_table_inherits/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_create_table_inherits/postgresql/stdlib/schema.sql, internal/endtoend/testdata/ddl_create_table_invalid_inherits/postgresql/stdlib/query.sql, internal/endtoend/testdata/ddl_create_table_invalid_inherits/postgresql/stdlib/schema.sql, internal/endtoend/testdata/ddl_create_table_invalid_inherits/postgresql/stdlib/sqlc.json, internal/endtoend/testdata/ddl_create_table_invalid_inherits/postgresql/stdlib/stderr.txt, internal/sql/catalog/table.go
Add tests for https://github.com/kyleconroy/sqlc/pull/2089
Implement constraint merging and add error handling for mismatched types
=> postgres: Column merging for table inheritence

.gitignore, devenv.lock, devenv.nix, devenv.yaml
Create a consistent development environment for sqlc using https://devenv.sh. This setup is completely optional.
=> build: Configure dependencies via devenv.sh

internal/cmd/cmd.go
`sqlc init` now would generate v2 format yaml file by default, user also can use `--v1` to generate v1 format if needed.
```
Create an empty sqlc.yaml settings file
Usage:
sqlc init [flags]
Flags:
-h, --help   help for init
--v1     generate v1 config yaml file
--v2     generate v2 config yaml file (default true)
```
=> improve init command to create v2/v1 yaml file

examples/booktest/sqlite/query.sql.go, internal/codegen/golang/templates/stdlib/queryCode.tmpl, internal/endtoend/testdata/sqlc_slice/mysql/go/models.go, internal/endtoend/testdata/sqlc_slice/mysql/go/query.sql.go, internal/endtoend/testdata/sqlc_slice/mysql/query.sql, internal/endtoend/testdata/sqlc_slice/sqlite/go/models.go, internal/endtoend/testdata/sqlc_slice/sqlite/go/query.sql.go, internal/endtoend/testdata/sqlc_slice/sqlite/query.sql
The generated code use a var named `sql` but when the query return a `database/sql` type like `sql.NullString` then the var is shadowing the import.
Fixes #1816
=> fix: MySQL slice shadowing database/sql import

internal/cmd/cmd.go
Also use the cobra helpers to avoid printing to stdout directly
=> cmd/sqlc: Show helpful output on missing subcommand

docs/reference/config.md, internal/cmd/shim.go, internal/codegen/golang/field.go, internal/codegen/golang/gen.go, internal/config/config.go, internal/config/v_one.go, internal/plugin/codegen.pb.go, internal/plugin/codegen_vtproto.pb.go
If json_tags_id_camelcase is true, "ID" in json tags will be camelcase. If false, will be uppercase. Defaults to `false`
Example where false:
```
type Example struct {
ID           uuid.UUID  `json:"id"`
Name         string     `json:"name"`
CreatedAt    time.Time  `json:"createdAt"`
UpdatedAt    time.Time  `json:"updatedAt"`
CreatedByID  *uuid.UUID `json:"createdByID"`
UpdatedByID  *uuid.UUID `json:"updatedByID"`
}
```
Example where true:
```
type Example struct {
ID           uuid.UUID  `json:"id"`
Name         string     `json:"name"`
CreatedAt    time.Time  `json:"createdAt"`
UpdatedAt    time.Time  `json:"updatedAt"`
CreatedByID  *uuid.UUID `json:"createdById"`
UpdatedByID  *uuid.UUID `json:"updatedById"`
}
```
=> Add json_tags_id_camelcase configuration option

buf.yaml, examples/python/sqlc.json, internal/endtoend/testdata/emit_pydantic_models/sqlc.json, internal/endtoend/testdata/exec_result/python_postgresql/sqlc.json, internal/endtoend/testdata/exec_rows/python_postgresql/sqlc.json, internal/endtoend/testdata/query_parameter_limit/-1/python_postgresql/sqlc.json, internal/endtoend/testdata/query_parameter_limit/0/python_postgresql/sqlc.json, internal/endtoend/testdata/query_parameter_limit/2/python_postgresql/sqlc.json
This version is build using the upcoming WASI support in Go 1.21.
=> python: Use latest version of sqlc-gen-python

examples/batch/postgresql/batch.go, internal/codegen/golang/templates/pgx/batchCode.tmpl, internal/endtoend/testdata/batch/postgresql/pgx/v4/go/batch.go, internal/endtoend/testdata/batch/postgresql/pgx/v5/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/v4/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/v5/go/batch.go, internal/endtoend/testdata/output_file_names/pgx/v4/go/batch_gen.go, internal/endtoend/testdata/output_file_names/pgx/v5/go/batch_gen.go
=> Don't defer rows.Close() if pgx.BatchResults.Query() failed 

docs/reference/config.md
Fixes https://github.com/kyleconroy/sqlc/pull/2349
=> docs: Update query_parameter_limit documentation

internal/codegen/golang/imports.go, internal/codegen/golang/query.go, internal/codegen/golang/templates/stdlib/queryCode.tmpl, internal/compiler/resolve.go, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/go/models.go, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/go/query.sql.go, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/query.sql, internal/endtoend/testdata/sqlc_slice/postgresql/stdlib/go/query.sql.go
=> Fix broken interaction between query_parameter_limit and pq.Array()

examples/authors/sqlc.json, examples/booktest/sqlc.json, examples/ondeck/sqlc.json, internal/cmd/vet.go, internal/endtoend/vet_test.go, internal/sqltest/postgres.go, internal/sqltest/sqlite.go
Using a bit of a hack for the examples to work in tests, as they use an in-memory database. For others, using a local file will also work.
=> feat(cmd/vet): Prepare SQLite queries

docs/guides/migrating-to-sqlc-gen-kotlin.md, docs/guides/migrating-to-sqlc-gen-python.md, docs/reference/config.md, docs/reference/language-support.rst, internal/codegen/golang/imports.go, internal/endtoend/testdata/datatype/stdlib/go/models.go, internal/endtoend/testdata/emit_pointers_for_null_types/stdlib/go/models.go, internal/endtoend/testdata/func_return/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/go.mod, internal/endtoend/testdata/go.sum, internal/endtoend/testdata/json/postgresql/stdlib/go/models.go
Fixes https://github.com/kyleconroy/sqlc/issues/2417
=> chore: replace codegen, test and docs references to github.com/tabbed repos

docs/howto/vet.md
`sqlc/db-prepare` was misspelled, updating to match the rule name properly
=> Fix: Update sqlc/db-prepare command name in docs

internal/sql/astutils/rewrite.go
=> fix: fix rewrite to traverse Sel in ast.In

docs/howto/select.md, internal/tools/sqlc-pg-gen/main.go
I added a description to the document for cases when a query result has no rows because I found it unclear what the query returns when reading the document.
=> docs: Add a description to the document for cases when a query result has no rows

internal/compiler/parse.go, internal/compiler/query.go, internal/metadata/meta.go, internal/metadata/meta_test.go
This is just a starting point for implementing the proposal in https://github.com/kyleconroy/sqlc/issues/2454.
For now I just parse comment lines starting with `@<string>` as `true`-valued boolean flags associated with a query.
I have another PR coming that uses this for sqlc vet rule opt-out.
=> feat: add basic parsing of boolean flag query metadata annotations

docker-compose.yml
By default, only the PostgreSQL 15 and MySQL 8 containers will start. To start all version of MySQL and PostgreSQL, use the following command:
```
docker compose --profile mysql --profile postgres up
```
=> test: Add profiles to docker compose

devenv.nix
`psql` and `mysqlsh` will now be installed if using devenv.sh
=> build: Add psql and mysqlsh to devenv

docs/howto/vet.md, docs/reference/config.md
- add `database` configuration for sqlc vet debug example
- alter the rule for sqlc vet debug example to make it not fail
- add undocumented `omit_unused_structs` flag to config docs
=> docs: small updates

docs/reference/config.md
The emit_pointers_for_null_types option supports both pgx/v4 and pgx/v5 according to the tests:
https://github.com/kyleconroy/sqlc/tree/main/internal/endtoend/testdata/emit_pointers_for_null_types
Ensure that this is clear in the documentation.
=> Clarify option package support

docs/howto/vet.md, internal/cmd/vet.go, internal/endtoend/testdata/vet_failures/stderr.txt
When trying to implement a rule using `query.cmd`, I was never able to make it match anything, including the examples provided.
So here's a fix for the small typo :) 
Also, as I was debugging, the comment on `messsage Query` made it a bit unclear if I should match `:cmd` or just `cmd`, so changed the examples to be without `:`
=> fix(vet): query.cmd was always set to ":"

docs/guides/plugins.md, docs/howto/vet.md, docs/reference/changelog.md, docs/reference/config.md, docs/reference/language-support.rst
Don't update the installation instructions until v1.20 is live
=> docs: Point GitHub links to new repository location

internal/codegen/golang/field.go, internal/codegen/golang/imports.go, internal/codegen/golang/query.go, internal/codegen/golang/result.go, internal/endtoend/testdata/sqlc_embed/postgresql/stdlib/go/models.go, internal/endtoend/testdata/sqlc_embed/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/sqlc_embed/postgresql/stdlib/query.sql
I think the title of the PR is inappropriate because my English is not very good.
close #2458
=> fix(codegen/golang): fix sqlc.embed to work with pq.Array wrap

internal/codegen/golang/field.go, internal/codegen/golang/imports.go, internal/compiler/output_columns.go, internal/compiler/resolve.go, internal/sql/catalog/table.go, internal/sql/sqlerr/errors.go, internal/tools/sqlc-pg-gen/main.go
Changes:
- while doing some local debugging, I observed a lot of use of `\"%s\"` to quote strings in `Sprintf` calls. Go [formally supports the `%q` formatting directive](https://pkg.go.dev/fmt#hdr-Printing) for double quoting strings, so I replaced those.
- I added a newline to the nil reference callout.
=> myriad formatting changes

internal/engine/sqlite/convert.go
Sorry about that.
Fixed a build problem in the main branch caused by #2556 and #2554 being merged at the same time.
=> fix(engine/sqlite): fix compile error

internal/endtoend/testdata/column_as/mysql/go/models.go, internal/endtoend/testdata/column_as/mysql/go/query.sql.go, internal/endtoend/testdata/column_as/mysql/query.sql, internal/endtoend/testdata/column_as/postgresql/pgx/v4/go/models.go, internal/endtoend/testdata/column_as/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/column_as/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/column_as/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/column_as/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/column_as/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/column_as/postgresql/stdlib/go/models.go, internal/endtoend/testdata/column_as/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/column_as/postgresql/stdlib/query.sql, internal/endtoend/testdata/column_as/sqlite/go/models.go, internal/endtoend/testdata/column_as/sqlite/go/query.sql.go, internal/endtoend/testdata/column_as/sqlite/query.sql, internal/engine/sqlite/convert.go
=> fix(engine/sqlite): fixed detection of column alias without AS

.github/workflows/ci.yml, .github/workflows/gen.yml
So this technically "fixes" the issue of our govulncheck CI check failing, but brings up a question: should we really be soft-blocking a merge when this CI check fails? And if not, what's the point of running this check in CI, and should we just run it somewhere else.
=> fix(ci): bump go version for govulncheck in ci.yml

docs/reference/datatypes.md
English is not my native language, so I could be wrong, but my interpretation of the text was that pgx can only do multidimensional arrays, and nothing else. I think that's not right. Hope my commit corrects this.
Thanks for sqlc and best of luck with your company around it.
=> docs: Reword phrase about pgx and multidimensional arrays

go.mod, go.sum, internal/config/go_type.go, internal/endtoend/testdata/overrides_go_struct_tags/invalid_tags/stderr.txt, internal/endtoend/testdata/overrides_go_struct_tags/sqlite/go/models.go, internal/endtoend/testdata/overrides_go_struct_tags/sqlite/schema.sql, internal/endtoend/testdata/overrides_go_struct_tags/sqlite/sqlc.json
304ba5de1 didn't correctly handle struct tags whose
value contained a space. (My fault.)
Use a proper struct tag library with a dedicated parser
that handles all the edge cases. Less code, and better.
=> fix Go struct tag parsing

internal/sql/astutils/walk.go
From the Go docs:
>  "For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/tMQ9JcUOMcI
=> refactor(astutils): remove redundant nil check in `Walk`

internal/compiler/output_columns.go, internal/endtoend/testdata/select_star/mysql/go/query.sql.go, internal/endtoend/testdata/select_star/mysql/query.sql, internal/endtoend/testdata/select_star/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/select_star/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/select_star/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/select_star/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/select_star/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/select_star/postgresql/stdlib/query.sql, internal/endtoend/testdata/select_star/sqlite/go/query.sql.go, internal/endtoend/testdata/select_star/sqlite/query.sql
close #2569
close #1722
astutils.Search does not stop traversing in the middle, so it returns redundant table nodes under ast.RangeSubselect.
I solved this problem by adding a visitor to ast.RangeSubselect that does not traverse the child nodes of ast.RangeSubselect.
=> fix(compiler): Fix to not scan children under ast.RangeSubselect when retrieving table listing

internal/compiler/output_columns.go, internal/endtoend/testdata/comparisons/mysql/go/query.sql.go, internal/endtoend/testdata/comparisons/mysql/query.sql, internal/engine/dolphin/convert.go, internal/sql/ast/bool_expr_type.go
=> feat(mysql): Add parser support for IS [NOT] NULL

internal/endtoend/testdata/select_union/mysql/go/query.sql.go, internal/endtoend/testdata/select_union/mysql/query.sql, internal/endtoend/testdata/select_union/postgres/pgx/v4/go/query.sql.go, internal/endtoend/testdata/select_union/postgres/pgx/v4/query.sql, internal/endtoend/testdata/select_union/postgres/pgx/v5/go/query.sql.go, internal/endtoend/testdata/select_union/postgres/pgx/v5/query.sql, internal/endtoend/testdata/select_union/postgres/stdlib/go/query.sql.go, internal/endtoend/testdata/select_union/postgres/stdlib/query.sql, internal/engine/dolphin/convert.go
=> fix(engine/dolphin): Fixed problem that LIMIT OFFSET cannot be used with `UNION ALL`

internal/compiler/output_columns.go, internal/endtoend/testdata/schema_scoped_list/mysql/go/query.sql.go, internal/endtoend/testdata/schema_scoped_list/mysql/query.sql, internal/endtoend/testdata/schema_scoped_list/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/schema_scoped_list/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/schema_scoped_list/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/schema_scoped_list/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/schema_scoped_list/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/schema_scoped_list/postgresql/stdlib/query.sql
=> fix(compiler): support identifiers with schema

docs/reference/config.md
[#2682](https://github.com/sqlc-dev/sqlc/issues/2682)
=> docs: Missing emit_pointers_for_null_types configuration option in version 2 (#2682)

docs/howto/embedding.md, docs/howto/insert.md, docs/index.rst, docs/reference/macros.md
Add a new section on embedding structs
Fixes https://github.com/sqlc-dev/sqlc/issues/2679
=> docs: Document sqlc.* macros

internal/codegen/golang/postgresql_type.go
=> fix(codegen/golang): support name type

internal/ext/wasm/nowasm.go, internal/ext/wasm/runner.go, internal/ext/wasm/wasm.go
Fixes https://github.com/sqlc-dev/sqlc/issues/2724
=> fix(wasm): Move Runner struct to shared file

internal/config/convert/convert.go, internal/config/convert/convert_test.go
Fixes https://github.com/sqlc-dev/sqlc/issues/2653
=> fix(convert): Support YAML anchors in plugin options

docs/reference/config.md, internal/core/fqn.go
=> docs: clarify nullable override behavior

.github/workflows/ci.yml
This change significantly slows down the Windows build, but it's the only way I've found to fix the failures we're seeing.
=> build(windows): Downgrade to mingw 11.2.0

.github/workflows/ci.yml, docs/howto/managed-databases.md, examples/authors/sqlc.yaml, examples/batch/sqlc.json, examples/booktest/sqlc.json, examples/jets/sqlc.json, examples/ondeck/sqlc.json, internal/cmd/cmd.go, internal/cmd/generate.go, internal/cmd/vet.go, internal/config/config.go, internal/config/v_one.json, internal/config/v_two.json, internal/config/validate.go, internal/endtoend/vet_test.go, internal/quickdb/region.go
The newest `vet` feature is running rules against databases hosted by us. You don't need to have PostgreSQL running locally, we'll take care of everything for you. This feature will be included in the next release as a private beta. We're still working out kinks in our infrastructure.
```yaml
version: '2'
cloud:
project: "01HAQMMECEYQYKFJN8MP16QC41"
sql:
- schema: postgresql/schema.sql
queries: postgresql/query.sql
engine: postgresql
database:
managed: true
rules:
- sqlc/db-prepare
```
=> feat(vet): Run rules against a managed database

internal/endtoend/ddl_test.go, internal/endtoend/vet_test.go
GitHub does not populate secrets on pull requests sent from a forked repository. Skip tests that require these secrets when they aren't present.
=> chore(endtoend): Skip tests if secrets are missing

docs/howto/managed-databases.md, docs/index.rst
=> docs: Add managed databases to sidebar

internal/sqltest/hosted/db.go
Tests failed on https://github.com/sqlc-dev/sqlc/pull/2768 due to missing secrets
=> chore: Skip certain tests on PRs

internal/endtoend/testdata/insert_values/mysql/go/query.sql.go, internal/endtoend/testdata/insert_values/mysql/query.sql, internal/endtoend/testdata/insert_values/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/insert_values/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/insert_values/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/insert_values/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/insert_values/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/insert_values/postgresql/stdlib/query.sql, internal/endtoend/testdata/insert_values/sqlite/go/query.sql.go, internal/endtoend/testdata/insert_values/sqlite/query.sql, internal/engine/sqlite/convert.go
=> fix(engine/sqlite): Fix convert process for VALUES

docs/howto/overrides.md, docs/howto/rename.md, docs/index.rst, docs/reference/config.md, docs/reference/datatypes.md
Fix https://github.com/sqlc-dev/sqlc/issues/231
Fix https://github.com/sqlc-dev/sqlc/issues/593
=> docs: Pull renaming and type overrides into separate sections

docs/howto/ci-cd.md, scripts/bump-version/main.go
Also improve the bump-version script to include docs and sqlc-version fields in YAML documents.
=> docs: Add sqlc upload to CI / CD guide

internal/endtoend/testdata/any/pgx/v4/go/query.sql.go, internal/endtoend/testdata/any/pgx/v4/query.sql, internal/endtoend/testdata/any/pgx/v5/go/query.sql.go, internal/endtoend/testdata/any/pgx/v5/query.sql, internal/endtoend/testdata/any/stdlib/go/query.sql.go, internal/endtoend/testdata/any/stdlib/query.sql, internal/endtoend/testdata/comment_godoc/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/comment_godoc/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/comment_godoc/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/comment_godoc/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/comment_godoc_db_argument/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/comment_godoc_db_argument/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/comment_godoc_db_argument/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/comment_godoc_db_argument/postgresql/pgx/v5/query.sql
These test cases weren't valid when sent to a running PostgreSQL database.
=> test: Fix a few incorrect testcases

docs/howto/structs.md
* Update docs/howto/structs.md
Added a link to the configuration reference on the JSON tags session.
=> docs: add clarity and reference to JSON tags

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, docs/reference/config.md, docs/tutorials/getting-started-mysql.md, docs/tutorials/getting-started-postgresql.md, docs/tutorials/getting-started-sqlite.md, internal/cmd/generate.go, internal/endtoend/ddl_test.go, internal/endtoend/endtoend_test.go, scripts/regenerate/main.go
Update `generate.go` to support the `.yml` extension, and also update the documentation files to explicitly indicate the option of using this extension. This is purely a quality of life update.
=> feat(generate): support yml extension

internal/engine/postgresql/analyzer/analyze.go
The connection pool config was there before I was closing the pool after analysis. The short connection lifespan was causing connection churn.
=> fix(postgresql): Remove temporary pool config

internal/cmd/shim.go, internal/cmd/vet.go, internal/compiler/compile.go, internal/compiler/parse.go, internal/compiler/query.go, internal/endtoend/testdata/comment_syntax/mysql/go/query.sql.go, internal/endtoend/testdata/invalid_queries_foo/pgx/v4/stderr.txt, internal/endtoend/testdata/invalid_queries_foo/pgx/v5/stderr.txt, internal/endtoend/testdata/invalid_queries_foo/stdlib/stderr.txt, internal/engine/dolphin/parse.go, internal/engine/postgresql/parse.go, internal/engine/sqlite/parse.go, internal/metadata/meta.go, internal/metadata/meta_test.go, internal/source/code.go
Groundwork for https://github.com/sqlc-dev/sqlc/issues/2800 (explicit type annotations in query comments metadata).
There are lots of tests that failed while I was refactoring this, so I have a fairly high degree of confidence that this refactor doesn't break anything. The changed endtoend test output is due to parsing bugs I fixed.
I chose to add a new `Metadata` struct type to house the growing set of stuff we associate with a query, but I don't have to so let me know if an alternative approach is preferred.
=> feat(compiler): Parse query parameter metadata from comments

Makefile, docker-compose.yml, docs/guides/development.md, go.sum
small changes to development.md file and makefile
- updates to use [docker compose v2](https://docs.docker.com/compose/)
- fixes environment variable for MYSQL_DATABASE was causing failing tests when running `make test-examples`
I'm new to this repo and to contributing, please let me know if i had missed anything.
=> patch: use docker compose v2 and update MYSQL_DATABASE env var

internal/endtoend/endtoend_test.go
Now that these tests run a bit faster, let's run them during all CI runs (that have an auth key)
=> test(endtoend): Enabled managed-db tests in CI

internal/cmd/cmd.go, internal/cmd/createdb.go, internal/config/config.go, internal/config/v_one.go, internal/config/v_two.json
Add a new `createdb` subcommand to sqlc. This creates an ephemeral database and prints the database URL for that database.
=> feat(createdb): Create ephemeral databases

internal/cmd/cmd.go, internal/cmd/vet.go, internal/engine/postgresql/analyzer/analyze.go, internal/opts/debug.go, internal/shfmt/shfmt.go, internal/shfmt/shfmt_test.go
- Remove the --no-database flag
- Refactor the shfmt package
=> feat(debug): Add databases=managed debug option

.github/workflows/ci.yml, go.mod, go.sum, internal/ext/wasm/wasm.go
This upgrade should fix the broken Windows build.
=> build(deps): Upgrade wasmtime-go from 13.0.0 to 14.0.0

internal/codegen/golang/enum.go
Just tiny change for single file:
* removed `strings.Title` cause this function is deprecated
* removed regexp, cause this expression easily converts to `strings.Map`
* replaced multiple `strings.Replace` to simple, fast and single line solution
* Added docs cuz why not? ¯\\\_(ツ)_/¯
Why this pr? I just probing how good contribution pipeline is for this repo, wanna make a lot of good improvements 😊
=> refactor(codegen): Removed deprecated code and improved speed

internal/codegen/golang/field.go, internal/codegen/golang/gen.go, internal/codegen/golang/go_type.go, internal/codegen/golang/imports.go, internal/codegen/golang/opts/options.go, internal/codegen/golang/postgresql_type.go, internal/codegen/golang/result.go
Pure refactor, to declutter future PRs
=> refactor(codegen/golang): Pull opts into its own package

internal/ext/wasm/wasm.go
When developing or using a plugin locally, having to update the configuration file every time to pull in a SHA256 can be very annoying. When fetching a plugin for the first time via HTTP, you may not know the SHA256 of the file you're fetching.
I've changed the plugin fetching behavior to calculate the SHA256 if it's not present. This results in extra network requests or filesystem reads, so it's still advised to set the SHA256, especially if it's not changing.
Before release, we'll add some logging to make it clear the extra requests are happening.
```
2023/11/02 10:10:49 WARN fetching WASM binary to calculate sha256. Set this value in sqlc.yaml to prevent unneeded work sha256=c8c759e80b7d66c728cf9d37674f8f5c9cc33774afa789dbceee0e3446773458
```
=> feat(plugin): Calculate SHA256 if it does not exist

internal/codegen/golang/opts/options.go, internal/config/config.go, internal/config/v_one.go, internal/config/v_two.go, internal/endtoend/testdata/query_parameter_limit_invalid/postgresql/query.sql, internal/endtoend/testdata/query_parameter_limit_invalid/postgresql/schema.sql, internal/endtoend/testdata/query_parameter_limit_invalid/postgresql/sqlc.json, internal/endtoend/testdata/query_parameter_limit_invalid/postgresql/stderr.txt
Resolves: https://github.com/sqlc-dev/sqlc/issues/2950
=> fix(codegen/golang): Move more Go-specific config validation into the plugin

internal/cmd/createdb.go
At least send the request to the endpoint if the engine is MySQL
=> feat(createdb): Add support for MySQL

buf.yaml, protos/buf.yaml
This removes the "protos" name from the import path.
=> build(buf): Change root of Buf module

internal/sql/sqlpath/read_test.go
This Pull Request enhances the sqlpath package by adding new tests for the Glob function, focusing on its ability to handle special pattern characters such as *, ?, [, and ]
Changes:
- Tests for * Pattern: Ensuring Glob correctly identifies SQL files in subdirectories matching a specified pattern.
- Tests for ? Character: Verifying Glob's functionality with patterns containing ?, representing a single unknown character.
- Tests for [ and ] Characters: Assessing Glob's ability to filter files using character ranges.
=> test: add glob pattern tests to sqlpath.Glob

internal/codegen/golang/opts/options.go
There is an error in the 1.24.0 in the Options file for golang codegen: the yaml annotation should be `output_querier_file_name` instead of `output_queries_file_name` for the `OutputQuerierFileName`
=> fix(codegen): wrong yaml annotation in go codegen options for output_querier_file_name

internal/engine/postgresql/analyzer/analyze.go
Postgres sometimes returns incorrect values for attndims which explains the TODO in the code. Use the type-derived dimensions instead.
This fixes a bug where in rare cases arrays were not correctly detected in one of our applications.
According to https://postgrespro.com/list/thread-id/2304332
> We don't really care.  attndims is a historical leftover and should never
be relied on for any semantically significant purpose.
TBH, my inclination would be to remove the column altogether rather than
"fix" this.
=> fix: Use derived ArrayDims instead of deprecated attndims

internal/engine/postgresql/analyzer/analyze.go
Fixes a bug introduced by https://github.com/sqlc-dev/sqlc/pull/3032
The end-to-end tests on that PR didn't fail as the database-based backed analyzer only runs on PRs created in this repo, which is a bug we'll need to fix soon.
We need to keep reading the value from the column definition for a specific reason
> The current implementation does not enforce the declared number of dimensions either. Arrays of a particular element type are all considered to be of the same type, regardless of size or number of dimensions. So, declaring the array size or number of dimensions in CREATE TABLE is simply documentation; it does not affect run-time behavior.
This means that arrays that should contain arrays of arrays of strings, could just contain an array of strings. We'll need to figure out how to …
=> fix: Take the maximum array dimensions

.github/workflows/ci-typescript.yml
Now that TypeScript support has landed, let's make sure to run it as part of our build process
=> build(typescript): Test against sqlc-gen-typescript

internal/cmd/vet.go, internal/cmd/vet_modernc.go, internal/sqltest/sqlite.go, internal/sqltest/sqlite_modernc.go
I've been experimenting with compiling the sqlc CLI to WASI. To get this to work, the `modernc.org/sqlite` package needs to be excluded from the build, as it doesn't support the WASI target.
```
CGO_ENABLED=0 GOOS=wasip1 GOARCH=wasm go build -o sqlc.wasm ./cmd/sqlc
```
=> build(sqlite): Disable modernc for WASM

go.mod, go.sum
=> build(deps): Upgrade to latest version of github.com/wasilibs/go-pgquery

docs/howto/embedding.md
I encountered a syntax error when attempting to directly copy and paste the SQL code from the sqlc.embed sample. 
I adjusted the param to align with the actual values.
=> docs: fix sample sql parameters for direct usability

docs/howto/ddl.md
The list for details about each migration tool didn't match the bullet-point list at the beginning of the section. It's a bit confusing for unsuspecting readers to see an item at position 2 but not find it as the second item in the expanded description.
=> re-order the migration tools list

go.mod, go.sum, internal/engine/sqlite/convert.go, internal/engine/sqlite/parse.go, internal/engine/sqlite/parser/Makefile, internal/engine/sqlite/parser/sqlite_lexer.go, internal/engine/sqlite/parser/sqlite_parser.go, internal/engine/sqlite/parser/sqliteparser_base_listener.go, internal/engine/sqlite/parser/sqliteparser_listener.go
=> chore(engine/sqlite): update to antlr 4.13.1

internal/codegen/golang/mysql_type.go, internal/endtoend/testdata/datatype/mysql/go/models.go, internal/endtoend/testdata/vet_explain/mysql/db/models.go, internal/endtoend/testdata/vet_explain/mysql/db/query.sql.go
Resolves https://github.com/sqlc-dev/sqlc/issues/3088
=> fix(codegen/golang): Use `int16` for MySQL `SMALLINT` and `YEAR`

Dockerfile
By changing our base to distroless/base, we make sure that our image has the correct SSL/TLS root certificates.
Originally reported by [denge6629](https://discord.com/channels/946447283321438248/1192745342597333052/1192745342597333052) in Discord.
=> fix(docker): Use distroless instead of scratch

docs/reference/datatypes.md
This PR adds instructions on how to use sqlc with PostGIS via [GEOS](https://libgeos.org) (the standard library for geometry operations, as used by PostGIS itself) and [go-geos](https://github.com/twpayne/go-geos) (the official Go bindings for GEOS).
=> docs: Add instructions for PostGIS/GEOS

internal/cmd/cmd.go
The `--experimental` flag was deprecated and later removed from the projects code. However, it seems that the command was not removed from the persistent `FlagSet`. Now this is confusing as it appears on the help list but it is not implemented.
=> Remove --experimental flag from the persistent FlagSet

docs/howto/named_parameters.md
The `@` operator shortcut for `sqlc.arg()` is not supported for mysql. This is confusing users and it needs to be specified in the documentation. This confusion is evident in the issue #3181 and the developer has even mention the documentation. Clearly stating that the operator is not supported for mysql will ensure developers do not mark it as a bug.
=> Add note specifying unsupported @ operator for mysql

examples/booktest/postgresql/db_test.go, examples/booktest/postgresql/query.sql, examples/booktest/postgresql/query.sql.go, examples/booktest/postgresql/schema.sql
Call DB function named `say_hello` for test.
=> test: Call say_hello function for test

docs/guides/development.md
Add `sqlc-gen-json` installation step to avoid the following error when tests running.
```
--- FAIL: TestReplay (0.13s)
--- FAIL: TestReplay/base/process_plugin_sqlc_gen_json (0.01s)
endtoend_test.go:231: sqlc generate failed: # package jsonb
error generating code: process: sqlc-gen-json not found
FAIL
FAIL	github.com/sqlc-dev/sqlc/internal/endtoend	2.156s
```
1. Clone the repo (I tried the latest commit: 8d7ec15953725dde6c0dc4d55bc20c0304fd1b01)
2. Run tests by `go test ./...` command
3. The error occurs
=> docs: Avoid test failure

docs/tutorials/getting-started-mysql.md, docs/tutorials/getting-started-postgresql.md
Fix incorrect links in the document.
=> docs: Fix incorrect links

docs/reference/datatypes.md
This is a small PR on the docs to help the developers to understand how the TEXT datatype works. I struggled a lot trying to override  a TEXT column to a `string`
=> docs(datatypes): improve details on TEXT

internal/endtoend/endtoend_test.go, internal/endtoend/testdata/golang_initialisms_url/schema.sql, internal/endtoend/testdata/golang_invalid_sql_package/schema.sql, internal/endtoend/testdata/schema_scoped_filter/mysql/schema.sql, internal/pgx/poolcache/poolcache.go, internal/sqltest/local/postgres.go, scripts/cleanup-test-dbs/main.go
- Run managed database tests in CI
- Support creating read-only databases
=> test(endtoend): Re-use databases when possible

docs/overview/install.md
Go 1.21+ is required for recent versions of sqlc. This is because it uses components that require the 1.21 toolchain. Coincidentally 1.21 is also when forward compatibility was introduced.
You can test this
```
$ docker run -it --rm golang:1.19
% go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
...
pkg/mod/github.com/sqlc-dev/sqlc@latest/internal/bundler/upload.go:7:2: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)
pkg/mod/github.com/sqlc-dev/sqlc@latest/internal/codegen/golang/opts/options.go:6:2: package maps is not in GOROOT (/usr/local/go/src/maps)
```
=> fix(docs): correct go install instructions

docker-compose.yml, internal/endtoend/endtoend_test.go, internal/endtoend/testdata/invalid_group_by_reference/mysql/query.sql, internal/endtoend/testdata/invalid_group_by_reference/mysql/schema.sql, internal/endtoend/testdata/invalid_group_by_reference/mysql/sqlc.json, internal/endtoend/testdata/invalid_group_by_reference/mysql/stderr.txt, internal/endtoend/testdata/valid_group_by_reference/mysql/schema.sql
Attempt to create a MySQL database for all the end-to-end tests. We haven't done this yet, so I expect this to fail.
=> test: Enabled MySQL database

docs/reference/config.md
The PR corrects grammar issue.
=> docs: Fix typo in config

examples/authors/mysql/db_test.go, examples/authors/postgresql/db_test.go, examples/authors/sqlite/db_test.go, examples/batch/postgresql/db_test.go, examples/booktest/mysql/db_test.go, examples/booktest/postgresql/db_test.go, examples/booktest/sqlite/db_test.go, examples/ondeck/mysql/db_test.go, examples/ondeck/postgresql/db_test.go, examples/ondeck/sqlite/db_test.go, internal/endtoend/vet_test.go, internal/engine/postgresql/parse_default.go, internal/engine/postgresql/parse_wasi.go, internal/engine/postgresql/parser/parser_default.go, internal/engine/postgresql/parser/parser_wasi.go
This PR removes outdated in Go 1.21 `// +build` comments by running the command:
```
go fix -fix buildtag ./...
```
From the https://pkg.go.dev/cmd/go#hdr-Build_constraints:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.
=> chore: remove deprecated build tags

docs/reference/language-support.rst
The C# plugin link was not working - the link target definition was missing
=> fix(docs): missing link target definition

internal/cmd/verify.go
While we were logging failures, we weren't returning an error to ensure that we exit with a non-zero code.
=> fix(verify): Return an error on failures

.github/workflows/ci.yml
It's unclear why this is happening, but our Windows builds have started timing out. Disable them while we figure out what's going on.
=> build: Disable Windows builds

internal/dbmanager/client.go
Lack of leading slash was causing database connections to fail whenever dbmanager tried to access a newly-created database.
=> fix(dbmanager): Add leading slash to db uri path rewrite

internal/cmd/createdb.go, internal/dbmanager/client.go
As part of phasing out hosted managed database support, the createdb command needed to be updated to use the new dbmanager package which talks directly to a PostgreSQL or MySQL server.
=> feat(createdb): Use locally running server for createdb command

docs/guides/migrating-to-sqlc-gen-kotlin.md
- "plugins" field takes "List" type not "Map".
- The example of the page written in different type, so I fixed example of setting
=> Fixed yaml example of "Migrating to sqlc-gen-kotlin" page

internal/dbmanager/client.go
If you create a database but can't connect to it, clean up after yourself
=> fix(dbmanager): Drop database if you can't connect

docs/howto/ddl.md
When using Goose with numeric migrations, if the migration files aren't in lexographic order SQLC parses them in the wrong order. This is similar to the issue that occurs with golang-migrate. This pr documents this behaviour.
=> fix(docs): Add ordering warning for numeric goose migration

internal/cmd/cmd.go
Didnt look much into details but there seems to be a typo here
=> fix(cmd): Read correct environment variable for remote

docs/howto/transactions.md
Update the documentation as described in issue #3192.
=> feat(docs): how-to use transactions with pgx

internal/dbmanager/client.go
Before this patch, `ManagedClient.CreateDatabase` could issue the following SQL:
```
DROP DATABASE mydb IF EXISTS WITH (FORCE)
```
which is not standard SQL and does not work with PostgreSQL. See https://www.postgresql.org/docs/current/sql-dropdatabase.html
This patch fixes to code to issue:
```
DROP DATABASE IF EXISTS mydb WITH (FORCE)
```
@kyleconroy , this patch fixes the DROP DATABASE syntax error introduced in https://github.com/sqlc-dev/sqlc/pull/3525 and https://github.com/sqlc-dev/sqlc/pull/3421
=> fix(dbmanager): use correct SQL to drop databases

internal/codegen/golang/reserved.go, internal/endtoend/testdata/params_go_keywords/postgresql/go/models.go, internal/endtoend/testdata/params_go_keywords/postgresql/go/query.sql.go, internal/endtoend/testdata/params_go_keywords/postgresql/query.sql, internal/endtoend/testdata/params_go_keywords/postgresql/schema.sql
Adds `q` to the reserve keywords.
Although not a golang keyword per se, it works as one since `q` is reserved as a shorthand for `Queries` in the generated code so there's no need to rename the reserved keywords list.
Fixes #3627.
=> fix(golang): escape q field name

docs/reference/config.md, docs/reference/query-annotations.md
Closes #3582
Adds documentation for `:copyfrom` query annotation.
Adds config reference for `sql_driver` required by `:copyfrom`.
None, this affects documentation only. Config json schema was not affected, `sql_driver` is already part of the schema.
Please squash before merging ( squash & merge on GH )
=> docs: add missing documentation about copyfrom

docs/tutorials/getting-started-sqlite.md
sqlc 1.25 removed the cgo dependency; updated the tutorial docs for sqlite to reflect this.
=> docs: Update tutorial to use modernc.sql/sqlite

internal/endtoend/testdata/inflection/mysql/go/models.go, internal/endtoend/testdata/inflection/mysql/go/query.sql.go, internal/endtoend/testdata/inflection/mysql/query.sql, internal/endtoend/testdata/inflection/mysql/schema.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v4/go/models.go, internal/endtoend/testdata/inflection/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v4/schema.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v5/go/models.go, internal/endtoend/testdata/inflection/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/inflection/postgresql/pgx/v5/schema.sql, internal/endtoend/testdata/inflection/postgresql/stdlib/go/models.go, internal/endtoend/testdata/inflection/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/inflection/postgresql/stdlib/query.sql, internal/endtoend/testdata/inflection/postgresql/stdlib/schema.sql, internal/endtoend/testdata/inflection/sqlite/go/models.go, internal/endtoend/testdata/inflection/sqlite/go/query.sql.go, internal/endtoend/testdata/inflection/sqlite/query.sql, internal/endtoend/testdata/inflection/sqlite/schema.sql, internal/inflection/singular.go
Fix [Table "bonuses" and "product_metadata" incorrectly generates model name. #3552](https://github.com/sqlc-dev/sqlc/issues/3552)
=> Fix incorrect generate model names for "metadata" suffix

docs/howto/vet.md, internal/cmd/vet.go, internal/compiler/parse.go, internal/constants/query.go, internal/endtoend/testdata/vet_disable/query.sql, internal/endtoend/testdata/vet_disable/sqlc.yaml, internal/endtoend/testdata/vet_disable/stderr.txt, internal/metadata/meta.go, internal/metadata/meta_test.go
This resolves #3619 and has some minor refactor in regards to reusable constants.
As mentioned there, the `@sqlc-vet-disable` query annotation now accepts a list of rules to skip:
```sql
/* @sqlc-vet-disable sqlc/db-prepare no-pg */
```
Providing just `/* @sqlc-vet-disable */` without any parameters retains the previous behaviour of skipping all rules for a query.
=> Allow selective disabling of rules per query

internal/ext/wasm/wasm.go
Fixes #3758
wazero takes care not to leak modules when `InstantiateModule` returns an error.
~This means that sqlc will call `result.Close` a second time if a non nil module was returned, which causes a segfault.~
Edit: this statement is wrong. See my comment below for the correct explanation of the segfault.
=> fix: Do not close wazero module on error (#3758)

docs/tutorials/getting-started-sqlite.md
The docs still reference the previously used `mattn/go-sqlite3`
=> docs: Fix sqlite package import

docs/reference/language-support.rst
hey,
i started working on a generator plugin for PHP with doctrine DBAL (see https://github.com/lcarilla/sqlc-plugin-php-dbal, i forked the kotlin plugin to have a base structure to build upon).
as of now it only supports mysql but i plan to properly integrate postgres and deal with issues with the plugin that might arise.
feel free to merge this PR which lists it under the Community language support section on the plugins page
=> new community generator plugin for PHP

.github/workflows/ci.yml
This PR replaced manual govulncheck installation with [golang/govulncheck-action](https://github.com/golang/govulncheck-action).
This will silence govulncheck as it's by default uses the latest patched Go version.
```
Run govulncheck ./...
govulncheck ./...
shell: /usr/bin/bash -e {0}
=== Symbol Results ===
Vulnerability #1: GO-[2](https://github.com/sqlc-dev/sqlc/actions/runs/13201723883/job/36855116383#step:5:2)025-3447
Timing sidechannel for P-256 on ppc64le in crypto/internal/nistec
More info: https://pkg.go.dev/vuln/GO-2025-[3](https://github.com/sqlc-dev/sqlc/actions/runs/13201723883/job/36855116383#step:5:3)447
Standard library
Found in: crypto/internal/nistec@go1.23.5
Fixed in: crypto/internal/nistec@go1.23.6
Platforms: ppc6[4](https://github.com/sqlc-dev/sqlc/actions/runs/13201723 …
```
=> build: Use govulncheck action

examples/authors/sqlite/db_test.go, examples/booktest/sqlite/db_test.go, examples/ondeck/sqlite/db_test.go, internal/sqltest/sqlite.go
The PR fixes `sqltest.SQLite` usages and implementation by adding the missing `sdb.Close()` and `source.Close()`.
`sqltest.SQLite` returns `*sql.DB`, which we need to close as shown here:
https://github.com/sqlc-dev/sqlc/blob/9cf5dbce1eaef8e81770d64c0fa07f02581f50a6/internal/endtoend/vet_test.go#L57-L59
[`os.CreateTemp`](https://pkg.go.dev/os#CreateTemp) creates a new temporary file in the directory `dir`, opens the file for reading and writing, and returns the resulting file. We also need to close it.
=> examples: Add missing Close calls

docs/reference/datatypes.md
It's `ST_Centroid`, not `ST_Centriod`. See https://postgis.net/docs/ST_Centroid.html
=> docs: Fix PostGIS function name

docs/reference/language-support.rst
I've got a new plugin for Zig that seems mostly stable and passes some basic tests. Figured I'd add it to the list to get it some exposure and start uncovering edge cases.
=> docs: Add Zig plugin

.github/workflows/ci.yml, Makefile, docs/guides/plugins.md, docs/reference/config.md, internal/cmd/generate.go, internal/config/config.go, internal/endtoend/testdata/process_plugin_format_json/exec.json, internal/endtoend/testdata/process_plugin_format_json/gen/hello.txt, internal/endtoend/testdata/process_plugin_format_json/query.sql, internal/endtoend/testdata/process_plugin_format_json/schema.sql, internal/endtoend/testdata/process_plugin_format_json/sqlc.json, internal/ext/process/gen.go, scripts/test-json-process-plugin/main.go
=> Add support for json format from process plugins

docs/reference/language-support.rst
I've been working on a plugin to [generate Java code](https://github.com/tandemdude/sqlc-gen-java) (so I can use it in my personal projects). This PR adds it to the list of community plugins. Currently working on finishing postgres support so I can start work on MySQL support. Hopefully someone can find it useful!
=> docs: add link to java plugin

internal/codegen/golang/postgresql_type.go
the only type accepted as a case for postgres type `timestamp` is `pg_catalog.timestamp`. It would be better if `timestamp` was also accepted directly, just as `timestamptz` is.
=> Update postgresql_type.go: accept "timestamp" as a case

docs/reference/language-support.rst
sqlc-gen-java now supports the MySQL engine - this PR updates the docs page accordingly.
=> docs: update supported engines for sqlc-gen-java

devenv.lock, devenv.nix, go.mod, go.sum, internal/codegen/golang/postgresql_type.go, internal/engine/postgresql/convert.go, internal/engine/postgresql/parse.go, internal/engine/postgresql/parse_default.go, internal/engine/postgresql/parser/parser_default.go, internal/engine/postgresql/utils.go
Fixes https://github.com/sqlc-dev/sqlc/issues/3836
=> build: Upgrade to wazero@v1.9.0

internal/codegen/golang/templates/pgx/queryCode.tmpl, internal/endtoend/testdata/wrap_errors/postgresql/pgx/db/query.sql.go
When wrapping errors, add a nil check before wrapping the error.
Fixes https://github.com/sqlc-dev/sqlc/issues/3912
=> fix(pgx): Do not wrap nil error

internal/migrations/migrations.go
This PR fixes an issue where SQLC was failing to properly detect and remove rollback statements in migration files due to case sensitivity. Previously, SQLC only recognized uppercase `Down` in rollback statements (e.g., `-- +goose Down`), but migration tools like Goose have updated their [documentation](https://pressly.github.io/goose/documentation/annotations/) to use lowercase `down` (e.g., `-- +goose down`).
The change makes the rollback statement detection case-insensitive by converting the statement to lowercase before checking, ensuring compatibility with:
- Both `-- +goose Down` and `-- +goose down` (Goose migrations)
- Both `-- +migrate Down` and `-- +migrate down` (sql-migrate)
- Case variations in other migration tool formats
This maintains backward compatibility with existing …
=> fix(migrations): case-sensitive migration rollback detection

internal/engine/dolphin/convert.go
`pcast.ChangeStmt` is deprecated, according to https://github.com/pingcap/tidb/issues/62912#issuecomment-3177527279
Resolves https://github.com/sqlc-dev/sqlc/issues/4046
Resolves https://github.com/pingcap/tidb/issues/62912
=> chore(engine/dolphin): remove references to deprecated `pcast.ChangeStmt`

docs/howto/rename.md
This update improves documentation for struct renaming in sqlc.yaml. 
- Adds an example showing how to handle multi-word table names, where underscores must be included (e.g., book_publisher → Publisher).
=> docs: add multi-worded table example for renaming
