sqlc-dev/sqlc

internal/dinosql/gen.go, internal/dinosql/testdata/ondeck/prepared/prepared.go
=> Only specify arguments one time

README.md
just a few suggestions to put the value prop front and center, tweak as you'd like!
=> hype up the readme

internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/dinosql/testdata/ondeck/db.go, internal/dinosql/testdata/ondeck/db_test.go, internal/dinosql/testdata/ondeck/prepared/prepared.go
=> Generate the correct integer types

internal/catalog/build.go, internal/catalog/build_test.go, internal/dinosql/parser_test.go, internal/pg/catalog.go, internal/pg/pg_catalog.go
Trying to contribute a little myself here 😃 
- turned the `Funcs` field of `Schema` into a map, having a slice there was difficult to work with in `catalog.Update()`
- sprinkled a few TODOs that I think might need addressing for proper function support
Happy to contribute more, this is a fun project 😃
=> capture CREATE FUNCTION statements into catalog

internal/catalog/build.go, internal/catalog/build_test.go, internal/dinosql/checks.go, internal/pg/catalog.go
This should get another small step closer to _nice_ argument struct field names. Only the recording bits to supported the added test cases, nothing more yet.
=> catalog: differentiate functions with different argument types

internal/cmd/cmd.go, internal/dinosql/parser.go
Line and column numbers are still incorrect
=> cmd: Include filenames in error messages

README.md, examples/slice_arg.md
Adding a new example explaining the usage of the ANY operator
=> New example

internal/dinosql/checks.go, internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/parser.go
fixed generation of JSON tags, fixed the related tests and fixed a minor detail on a single for loop ranging a slice
fixes #86
=> JSON tags generation

internal/dinosql/gen.go
Fixes #88 
While this pull request addresses the issues in #88, it still doesn't fix the long term issue with schemas and structs. We'll need to figure out how and when to append schema names to structs.
=> gen: Include all schemas when generating models

internal/dinosql/gen.go
If a table or enum belongs to a schema outside the public schema, prefix
structs with that schema name.
Truly fixes #88
=> gen: Prefix structs with schema name

internal/dinosql/gen.go, internal/dinosql/gen_test.go
Support to bytea added, passed the test in gen_test.go, not sure if it will work in all situations, please review
=> Bytea support

internal/dinosql/parser.go
=> parser: Correctly handle single files

internal/dinosql/gen.go, internal/dinosql/parser.go, internal/dinosql/parser_test.go, internal/dinosql/testdata/ondeck/db.go, internal/dinosql/testdata/ondeck/prepared/db.go
=> Validate query name

internal/dinosql/gen.go
=> proper generated code to handle byte slices

internal/dinosql/gen.go
#138 fixed #137, but included logging statements. Remove them.
=> Remove logging statements

internal/dinosql/soup.go
=> internal/dinosql: Dereference alias nodes on walk

internal/dinosql/parser.go, internal/dinosql/query_test.go, internal/postgres/types.go
=> internal/dinosql: Quote reserved keywords

internal/dinosql/gen.go
Add another synonym for int4 data type.
=> Add another synonym for int32 type

internal/mysql/parse.go
=> log filename of unparsable mysql schema file

internal/mysql/param.go, internal/mysql/parse.go, internal/mysql/parse_test.go
Addresses #254 
This fixes the most blatant cases of update queries without where clauses.
=> adds support or update queries without where

internal/mysql/parse.go, internal/mysql/parse_test.go
Addresses #253 
I think this should fix the issue described. Surely there are still combinations that are still broken, but this should work for the specific query composition shown in the issue.
=> adds support for select expression as insert query rows

docs/annotations.md
=> docs: Add documentation for query commands

internal/mysql/errors_test.go, internal/mysql/gen_test.go, internal/mysql/parse.go, internal/mysql/parse_test.go
Improves the test coverage for `mysql` code generation
=> improves mysql generation test coverage

internal/mysql/gen.go
=> patches mysql support for bool types

internal/cmd/cmd.go, internal/dinosql/config.go, internal/dinosql/gen.go, internal/dinosql/gen_test.go, internal/dinosql/parser.go, internal/endtoend/endtoend_test.go, internal/mysql/errors_test.go, internal/mysql/gen.go, internal/mysql/gen_test.go, internal/mysql/param.go, internal/mysql/param_test.go, internal/mysql/parse.go, internal/mysql/parse_test.go
Create a new `CombinedSettings` struct that includes the global settings
and the current package settings.
Fixes #293
=> internal: Remove the PackageMap from settings

examples/booktest/mysql/models.go, examples/booktest/mysql/query.sql, examples/booktest/mysql/query.sql.go, examples/booktest/mysql/schema.sql, internal/mysql/param.go
=> patches param replacement matching for double digits

internal/dinosql/parser.go
=> internal/parser: Remove print statement

.github/workflows/equinox.yml, internal/cmd/cmd.go, scripts/release.go
Fixes #335 
```
$ sqlc version
v0.0.0-20200211210845-1a5e1419b3bf
```
=> Write a release script

internal/cmd/cmd.go
=> cmd: Include the version by default

internal/catalog/build.go, internal/endtoend/testdata/builtins/query.sql
Actually support "create schema if not exists sqlc"
=> Add support for create-if-not-exists for 'create schema'

internal/dinosql/gen.go, internal/dinosql/kotlin/gen.go
Support multi-line comments on columns.
Similar to #345, but for columns.
=> Fix column comment

internal/postgresql/catalog_test.go, internal/postgresql/parse.go, internal/sql/catalog/catalog.go, internal/sql/catalog/comment_on.go, internal/sql/catalog/func.go, internal/sql/catalog/schema.go, internal/sql/catalog/table.go, internal/sql/catalog/types.go, internal/sql/sqlerr/errors.go
Rename the sql/errors package to sql/sqlerr
Remove spew from PostgreSQL parser
Fix table renaming bug
=> sql/catalog: Port tests over from catalog package

Makefile, internal/cmd/cmd.go, internal/cmd/generate.go, internal/compiler/compile.go, internal/compiler/engine.go, internal/endtoend/endtoend_test.go
It's gated behind a environment variable that has no effect in
production builds.
=> Add the experimental parser in tests

docs/migrations.md
Sorry for missing that in my commit. 
Thanks for this awesome tool :heart:
=> Add dbmate link to migration docs

internal/cmd/cmd.go, internal/codegen/golang/enum.go, internal/codegen/golang/struct.go, internal/compiler/build_result.go, internal/compiler/compat.go, internal/compiler/compile.go, internal/compiler/expand.go, internal/compiler/find_params.go, internal/compiler/go_type.go, internal/compiler/output_columns.go, internal/compiler/parse.go, internal/compiler/query.go, internal/compiler/query_catalog.go, internal/compiler/resolve.go, internal/compiler/result.go, internal/compiler/to_column.go, internal/dinosql/gen.go, internal/mysql/gen.go, internal/sql/astutils/walk.go, internal/sql/catalog/catalog.go, internal/sql/catalog/public.go, internal/sql/catalog/table.go, internal/sql/lang/operator.go, internal/sql/rewrite/parameters.go, internal/sql/sqlerr/errors.go
=> Port the rest of the compiler to the new AST

internal/codegen/golang/go_type.go
=> golang: Add support for the money type

internal/mysql/parse.go, internal/mysql/schema.go
Ran into this error when trying to process a SQL file introducing a view, and
it was hard to chase down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kyleconroy/sqlc/608)
=> Return an error from Schema.Add when the table spec is nil

internal/mysql/schema.go
https://github.com/kyleconroy/sqlc/issues/610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kyleconroy/sqlc/613)
=> Handle MySQL renames

internal/compiler/output_columns.go, internal/endtoend/testdata/coalesce/go/models.go, internal/endtoend/testdata/coalesce/go/query.sql.go, internal/endtoend/testdata/coalesce/query.sql
=> compiler: Return a single column from coalesce

scripts/regenerate.sh
This includes the `postgresql` and `mysql` subdirectories of some of the test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kyleconroy/sqlc/650)
=> Update regenerate.sh to include all recursive subdirs containing a sqlc.json

internal/codegen/golang/mysql_type.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kyleconroy/sqlc/652)
=> Support MySQL JSON type

README.md
=> Improve README/Settings

.github/dependabot.yml
Add dependabot,yml. 
This automatically creates a pull request for dependency updates.
[About Dependabot version updates - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates)
=> 👷  add: dependabot.yml

Makefile, internal/endtoend/testdata/json_build/go/query.sql.go, internal/endtoend/testdata/json_build/query.sql, internal/engine/postgresql/pg_catalog.go, internal/sql/catalog/catalog.go, internal/sql/catalog/public.go
Thanks to @ovadbar for the suggestions
=> catalog: Improve variadic argument support

internal/codegen/golang/field.go, internal/endtoend/testdata/emit_db_and_json_tags/go/models.go
=> Fix (golang) multiple struct tag formatting 

internal/codegen/golang/imports.go, internal/endtoend/testdata/macaddr/go/query.sql.go, internal/endtoend/testdata/macaddr/query.sql
Add a map of known types to always check
Fixes #853
=> codegen/golang: Make sure to import net package

docs/howto/prepared_query.md
Fix typo: perpared -> prepared
=> Fix Readme typo

internal/cmd/cmd.go
=> cmd: Fix sqlc init

.github/workflows/ci-kotlin.yml
=> Upgrade to setup-java/v2

internal/codegen/golang/result.go, internal/endtoend/testdata/ddl_create_enum/mysql/go/models.go, internal/endtoend/testdata/ddl_create_enum/mysql/go/query.sql.go, internal/endtoend/testdata/ddl_create_enum/mysql/schema.sql, internal/endtoend/testdata/ddl_create_enum/postgresql/go/models.go, internal/endtoend/testdata/ddl_create_enum/postgresql/schema.sql
I took a similar approach to #934 and added some tests.
Fixes #934 
Fixes #933
=> codegen: Generate valid enum names for symbols

internal/compiler/parse.go, internal/compiler/resolve.go, internal/endtoend/testdata/relation_does_not_exist/postgresql/query.sql, internal/endtoend/testdata/relation_does_not_exist/postgresql/sqlc.json, internal/endtoend/testdata/relation_does_not_exist/postgresql/stderr.txt
Fix panic when accessing defaultTable
Fixes #1051 
Fixes #1038
=> compiler: Return error if relation not found

internal/codegen/utils.go, internal/codegen/utils_test.go
Also added a test for empty string + some tests for the current behaviour.
=> fix for index out of range [0] in codegen.LowerTitle when input is empty

.github/workflows/docker.yml
=> Multi-arch Docker builds

docs/tutorials/getting-started.md
fix typo: fullowing -> following
=> getting-started.md: fix typo

docs/tutorials/getting-started-mysql.md, docs/tutorials/getting-started-postgresql.md
=> docs: Fix package name referenced in tutorial

go.mod, go.sum
=> fix(sqlite): Update ANTLR v4 go.mod entry

internal/cmd/generate.go
Fixes (in my opinion): https://github.com/kyleconroy/sqlc/issues/1365
=> Update error message

docs/reference/config.md
Fixes https://github.com/kyleconroy/sqlc/pull/1428
=> docs: Add more documentation for go_type

examples/ondeck/postgresql/querier.go, internal/codegen/golang/templates/pgx/interfaceCode.tmpl, internal/codegen/golang/templates/stdlib/interfaceCode.tmpl, internal/endtoend/testdata/copyfrom/postgresql/pgx/go/querier.go
=> feat(codegen): Insert comments in interfaces

internal/compiler/output_columns.go, internal/endtoend/testdata/join_left/mysql/go/models.go, internal/endtoend/testdata/join_left/mysql/go/query.sql.go, internal/endtoend/testdata/join_left/mysql/query.sql, internal/endtoend/testdata/join_left/postgresql/go/models.go, internal/endtoend/testdata/join_left/postgresql/go/query.sql.go, internal/endtoend/testdata/join_left/postgresql/query.sql
Related to: https://github.com/kyleconroy/sqlc/issues/1334
=> fix(compiler): Fix left join nullability with table aliases

.github/workflows/ci.yml, internal/config/config_test.go
=> config: Add basic fuzzing for config / overrides

README.md, docs/overview/install.md
* Add link in README
* Add link in docs
=> docs: Add links to downloads.sqlc.dev

internal/ext/wasm/wasm.go
Fixes https://github.com/kyleconroy/sqlc/issues/1704
=> feat: Set user-agent for plugin downloads

examples/batch/postgresql/models.go, examples/booktest/mysql/models.go, examples/booktest/postgresql/models.go, examples/ondeck/mysql/models.go, examples/ondeck/postgresql/models.go, internal/codegen/golang/templates/template.tmpl, internal/endtoend/testdata/comment_on/postgresql/pgx/go/models.go, internal/endtoend/testdata/comment_on/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_alter_type_add_value/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_alter_type_add_value/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename_and_update_columns/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename_and_update_columns/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename_value/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_alter_type_rename_value/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_comment/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_comment/postgresql/stdlib/go/models.go, internal/endtoend/testdata/ddl_create_enum/mysql/go/models.go, internal/endtoend/testdata/ddl_create_enum/postgresql/pgx/go/models.go, internal/endtoend/testdata/ddl_create_enum/postgresql/stdlib/go/models.go, internal/endtoend/testdata/emit_enum_valid_and_values/go/models.go, internal/endtoend/testdata/enum/mysql/go/models.go, internal/endtoend/testdata/enum/postgresql/pgx/go/models.go, internal/endtoend/testdata/enum/postgresql/stdlib/go/models.go, internal/endtoend/testdata/rename/pgx/go/models.go, internal/endtoend/testdata/rename/stdlib/go/models.go, internal/endtoend/testdata/schema_scoped_enum/pgx/go/models.go, internal/endtoend/testdata/schema_scoped_enum/stdlib/go/models.go
Fixes https://github.com/kyleconroy/sqlc/issues/1789
=> fix: Emit correct comment for nullable enums

Dockerfile
=> docker: Change ENTRYPOINT to CMD

internal/engine/dolphin/convert.go
=> fix(engine/mysql): take into account column's charset to distinguish text/blob, (var)char/(var)binary

Dockerfile
=> Revert "docker: Change ENTRYPOINT to CMD"

examples/batch/postgresql/batch.go, internal/codegen/golang/templates/pgx/batchCode.tmpl, internal/endtoend/testdata/batch/postgresql/pgx/v4/go/batch.go, internal/endtoend/testdata/batch/postgresql/pgx/v5/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/v4/go/batch.go, internal/endtoend/testdata/batch_imports/postgresql/pgx/v5/go/batch.go, internal/endtoend/testdata/emit_result_and_params_struct_pointers/postgresql/pgx/v4/go/batch.go, internal/endtoend/testdata/emit_result_and_params_struct_pointers/postgresql/pgx/v5/go/batch.go
=> Define base error in batch.go for better error handling

docs/guides/using-go-and-pgx.rst
=> Fixing Document Typo

internal/codegen/golang/struct.go
Creating a new pull request to re-run tests 
Replaces https://github.com/kyleconroy/sqlc/pull/1846
=> Fix hyphen in go struct names

.readthedocs.yaml, devenv.nix
Also add Python to the development environment.
=> docs: Add a ReadTheDocs config file

internal/compiler/resolve.go, internal/endtoend/testdata/between_args/mysql/go/query.sql.go, internal/endtoend/testdata/between_args/sqlite/go/query.sql.go
=> Improve default names for BETWEEN ? AND ? to have prefixes from_ and to_

internal/codegen/golang/gen.go, internal/codegen/golang/templates/stdlib/queryCode.tmpl
Handling it separately is just waiting for bugs to happen. Git-blame tells me the person to blame is .. me. Whoops.
=> codegen/golang: Bring :execlastid in line with the rest

.github/workflows/ci.yml, docker-compose.yml, examples/authors/sqlc.json, examples/booktest/sqlc.json, examples/ondeck/sqlc.json, internal/cmd/vet.go, internal/endtoend/vet_test.go, internal/sqltest/mysql.go, internal/sqltest/postgres.go
Add MySQL support to vet after PostgreSQL support landed in #2387
=> feat(cmd/vet): Prepare queries for MySQL

.github/workflows/ci.yml, .github/workflows/gen.yml, devenv.lock
=> build: Pin Go to 1.20.6

internal/endtoend/testdata/sqlc_arg/mysql/go/query.sql.go, internal/endtoend/testdata/sqlc_arg/mysql/query.sql
A fix was merged in https://github.com/kyleconroy/sqlc/pull/2414. This just adds a test case for https://github.com/kyleconroy/sqlc/issues/2403
=> Add an endtoend test that covers the case referenced in #2403

docker-compose.yml
MySQL 5.7, 8.0
PostgreSQL 11, 12, 13, 14, 15
=> build: Run all supported versions of MySQL / PostgreSQL

internal/codegen/golang/imports.go, internal/codegen/golang/sqlite_type.go
=> fix: sqlite log

docs/howto/ddl.md
This one caught me out for a little while and I had to find an example in issues.
Hopefully this helps others reading the docs!
=> Add example sqlc.yaml for migration parsing

docs/tutorials/getting-started-mysql.md
Updated the version of the configuration file in the MySQL tutorial from 1 to 2.
=> docs: Modify config file version of mysql tutorial

docs/guides/using-go-and-pgx.rst, scripts/regenerate/main.go
Resolves https://github.com/sqlc-dev/sqlc/issues/2566
=> fix: remove references to deprecated `--experimental` flag

internal/codegen/golang/templates/pgx/queryCode.tmpl, internal/codegen/golang/templates/stdlib/queryCode.tmpl, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/go/models.go, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/go/query.sql.go, internal/endtoend/testdata/query_parameter_limit_to_two/postgresql/query.sql
=> fix(codegen): Compare define type in codegen

examples/booktest/sqlite/db_test.go, examples/booktest/sqlite/query.sql.go, internal/endtoend/testdata/full_outer_join/sqlite/go/query.sql.go, internal/endtoend/testdata/join_left/sqlite/go/query.sql.go, internal/endtoend/testdata/join_left_same_table/sqlite/go/query.sql.go, internal/endtoend/testdata/join_where_clause/mysql/go/query.sql.go, internal/endtoend/testdata/join_where_clause/mysql/query.sql, internal/endtoend/testdata/join_where_clause/postgresql/pgx/v4/go/query.sql.go, internal/endtoend/testdata/join_where_clause/postgresql/pgx/v4/query.sql, internal/endtoend/testdata/join_where_clause/postgresql/pgx/v5/go/query.sql.go, internal/endtoend/testdata/join_where_clause/postgresql/pgx/v5/query.sql, internal/endtoend/testdata/join_where_clause/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/join_where_clause/postgresql/stdlib/query.sql, internal/endtoend/testdata/join_where_clause/sqlite/go/query.sql.go, internal/endtoend/testdata/join_where_clause/sqlite/query.sql, internal/engine/sqlite/convert.go
=> fix(engine/sqlite): Fix to handle join clauses correctly

docs/conf.py, docs/reference/changelog.md, docs/requirements.txt
Switch from the deprecated recommonmark to MyST
=> docs: Add stable anchors to changelog

internal/cmd/generate.go
resolves https://github.com/sqlc-dev/sqlc/issues/2716
=> feat(generate): reorder codegen handlers to prefer plugins

internal/codegen/golang/gen.go, internal/endtoend/testdata/omit_unused_structs/postgresql/stdlib/go/models.go, internal/endtoend/testdata/omit_unused_structs/postgresql/stdlib/go/query.sql.go, internal/endtoend/testdata/omit_unused_structs/postgresql/stdlib/query.sql, internal/endtoend/testdata/omit_unused_structs/postgresql/stdlib/schema.sql
Resolves https://github.com/sqlc-dev/sqlc/issues/2860
=> fix(codegen/go): Prevent filtering of embedded struct fields

internal/config/validate.go, internal/endtoend/testdata/star_expansion_series/postgresql/pgx/sqlc.yaml
Catch the unauthenticated error from the service instead.
=> feat(config): Remove managed database validation

internal/cmd/vet.go
resolves https://github.com/sqlc-dev/sqlc/issues/2933
=> fix(vet): Add a nil pointer check to prevent db/prepare panic

internal/cmd/generate.go, internal/endtoend/testdata/bad_config/engine/query.sql, internal/endtoend/testdata/bad_config/engine/sqlc.yaml, internal/endtoend/testdata/bad_config/engine/stderr.txt
Resolves https://github.com/sqlc-dev/sqlc/issues/2939
=> fix(compiler): Prevent panic when compiler is nil

internal/cmd/cmd.go
Resolves https://github.com/sqlc-dev/sqlc/issues/2979
=> fix: Update help text for generate to be more generic

internal/codegen/golang/gen.go, internal/endtoend/testdata/duplicate_go_names/enum/query.sql, internal/endtoend/testdata/duplicate_go_names/enum/schema.sql, internal/endtoend/testdata/duplicate_go_names/enum/sqlc.yaml, internal/endtoend/testdata/duplicate_go_names/enum/stderr.txt, internal/endtoend/testdata/duplicate_go_names/null_enum/query.sql, internal/endtoend/testdata/duplicate_go_names/null_enum/schema.sql, internal/endtoend/testdata/duplicate_go_names/null_enum/sqlc.yaml, internal/endtoend/testdata/duplicate_go_names/null_enum/stderr.txt, internal/endtoend/testdata/duplicate_go_names/query_constant/query.sql, internal/endtoend/testdata/duplicate_go_names/query_constant/schema.sql, internal/endtoend/testdata/duplicate_go_names/query_constant/sqlc.yaml, internal/endtoend/testdata/duplicate_go_names/query_constant/stderr.txt
Resolves https://github.com/sqlc-dev/sqlc/issues/588
=> fix: Return an error instead of generating duplicate Go names

internal/codegen/golang/imports.go, internal/endtoend/testdata/sqlc_slice/postgresql/pgx/go/models.go, internal/endtoend/testdata/sqlc_slice/postgresql/pgx/go/query.sql.go, internal/endtoend/testdata/sqlc_slice/postgresql/pgx/query.sql, internal/endtoend/testdata/sqlc_slice/postgresql/pgx/schema.sql
Also fix the invalid test that should have caught this.
Resolves https://github.com/sqlc-dev/sqlc/issues/3065
=> fix(codegen/golang): Don't import `"strings"` for `sqlc.slice()` with pgx

examples/authors/mysql/db_test.go, examples/authors/sqlc.yaml, examples/batch/sqlc.json, examples/booktest/mysql/db_test.go, examples/booktest/sqlc.json, examples/jets/sqlc.json, examples/ondeck/sqlc.json, internal/endtoend/vet_test.go
Also update the last two database tests to use local server.
=> test: Run vet against local database server

internal/endtoend/testdata/order_by_binds/mysql/go/query.sql.go, internal/endtoend/testdata/order_by_binds/mysql/query.sql, internal/endtoend/testdata/order_by_binds/postgresql/go/query.sql.go, internal/endtoend/testdata/order_by_binds/postgresql/query.sql, internal/engine/dolphin/convert.go
=> fix variables not resolving in mysql ORDER BY statements

internal/endtoend/case_test.go, internal/endtoend/testdata/wasm_plugin_sqlc_gen_unsafe_paths/stderr_windows.txt
Allow for OS specific stderr files
=> fix(endtoend): Fix unsafe paths test on Windows

go.mod, go.sum, internal/engine/postgresql/convert.go, internal/engine/postgresql/parse.go, internal/engine/postgresql/parse_default.go, internal/engine/postgresql/parser/parser_default.go, internal/engine/postgresql/utils.go, internal/sql/ast/aggref.go, internal/sql/ast/grant_role_stmt.go, internal/sql/ast/index_stmt.go, internal/sql/ast/op_expr.go, internal/sql/ast/scalar_array_op_expr.go
Also upgrade go-pgquery to latest
Closes https://github.com/sqlc-dev/sqlc/pull/3280
Closes https://github.com/sqlc-dev/sqlc/pull/3267
=> build(deps): bump wazero from 1.5.0 to 1.7.0

internal/cmd/vet.go
Make sure that `sqlc vet` works with the new managed database call path.
=> feat(vet): Use new dbmanager client

LICENSE, docs/conf.py
Updates the year in docs and LICENSE from 2023 to 2024
=> update: Set current year in docs and license

internal/cmd/verify.go, internal/dbmanager/client.go
Also print out more error info by default
=> fix(verify): Include database engine in request

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
It wasn't being used and just cluttered things
=> chore: Remove the triage label

docs/reference/language-support.rst
I've added sqlite support to my Zig plugin so figured I'd update the docs here
=> Add sqlite beta support for zig plugin

docs/reference/language-support.rst
Hi,
We have implemented all supported query annotations and macros for all three databases, and we have tests for most of the generated code features.
We think our plugin is stable now 💯  and would like to update the docs
=> update csharp support to stable

docs/howto/managed-databases.md
=> [typo] locahost → localhost
